### ISSUE TITLE
Safari not loading fonts with local src defined

### ISSUE THREAD

**Issue by mlev** [bramstein/fontfaceobserver#105]
I'm guessing this is a Safari issue but fonts defined with a local name in the src do not seem to get pre-loaded in Safari - even though the promise is resolved successfully.

e.g. something like this:

```
@font-face {
  font-family: 'Family1';
  font-style: normal;
  font-weight: normal;
  src: local('Family1'), url(https://url-to-font.woff2) format('woff2');
}
```

When loading this the promise will return successfully but the browser appears to make no effort to load the font - even if it is already in the browser cache. You can watch the network traffic and see that it isn't loaded until something uses it.

Here is a JS fiddle that waits for fonts before displaying on canvas. On first load the font with the local name displays unprintable chars and the font without is pre-loaded. If you remove the local name from the first then both work as expected.
https://jsfiddle.net/mlev/3w6wxzho/

I'm suppose the workaround is don't use local names. Is there something I'm missing?

**Comment by bramstein** [comment]
Hmm, that does seem like a Safari issue. I replaced the Font Face Observer calls with the native font loading API (which FFO uses when it is available), and got the same results:

https://jsfiddle.net/7gLr3vx9/

Both Chrome and Firefox handle this correctly. I'll ask someone from the WebKit team to take a look at this issue.

**Comment by litherum** [comment]
Hi! I thought I [fixed](https://trac.webkit.org/changeset/216079/webkit) this recently in Safari. Can you try in a [WebKit nightly build](https://webkit.org/nightly/) or a [iOS 11 / macOS High Sierra beta](https://beta.apple.com/sp/betaprogram/)?

**Comment by mlev** [comment]
Yeah - Webkit nightly build works for me - Version 10.1.1 (12603.2.4, r219195).

**Comment by litherum** [comment]
\o/

**Comment by bramstein** [comment]
@litherum Thanks for confirming, _and_ fixing the bug. 👍
