### ISSUE TITLE
Unclear errors + remove reliance on Promise.race

### ISSUE THREAD

**Issue by tyrw** [bramstein/fontfaceobserver#106]
When running a plain example as shown in the docs, getting a couple of errors related to `Promise.race` not being defined.

```js
let fontAwesomeFont = new FontFaceObserver('FontAwesome')
try {
  fontAwesomeFont.load()
  .then(res => console.log('loaded', res))
  .catch(err => console.log('err', err))
} catch (err) {
  console.log('caught', err)
}
```

Running this yields the `.catch` error with `Unhandled rejection TypeError: Promise.race is not a function`

And then another console warning message a few moments later with `Unhandled rejection undefined`.  This second one was all we were seeing initially until we went hunting for the first one.

It'd be nice to remove the dependency on `Promise.race` since it's not as widely supported and only appears to be used in this codebase one time.

**Comment by JakeChampion** [comment]
Which version of the fontfaceobserver polyfill are you using? If using `fontfaceobserver.standalone.js` then you will not receive a `Promise` polyfill.

**Comment by tyrw** [comment]
Using it without the polyfill as we already had our own.  For now our solution has just been to switch to a different polyfill (https://github.com/stefanpenner/es6-promise).
