### ISSUE TITLE
IE11 not loading font - Comparison with 'BESbswy'

### ISSUE THREAD

**Issue by gRoussac** [bramstein/fontfaceobserver#109]
Hi,

For IE it seems that you are comparing a text string to know if the font is loaded. However we believe that some fonts may not have any of the characters, or they might not be any difference for these chars. Maybe you should compare on innerHTML whether than pure text so that we can send html to load function for the comparison. For instance https://www.independer.nl/content/fonts/generic/generic.woff does not seem to resolve the promise because of that.

Best regards

**Comment by kennethormandy** [comment]
Hey, you’re correct that sometimes this needs to be configurable, but luckily Bram has already built this into the library. From [the docs](https://github.com/bramstein/fontfaceobserver/blob/master/README.md#how-to-use):

> If your font doesn't contain at least the latin "BESbwy" characters you must pass a custom test string to the `load` method.
> 
> ```js
> var font = new FontFaceObserver('My Family');
> 
> font.load('中国').then(function () {
>   console.log('Font is available');
> }, function () {
>   console.log('Font is not available');
> });
> ```

**Comment by gRoussac** [comment]
Hey,

Thanks for your answer. We tried that already but this was not working and I believe because of this line https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js#L22 wich is using a text function.

Would you mind testing that on IE 11 ? (working on Chrome tho)

http://jsfiddle.net/mgxzj987/13/    (http is important here sorry I had to host the font because of CSP, in network tab you may see the two fonts loaded)

Thanks again for your work and help.

**Comment by kennethormandy** [comment]
Hey, just to clarify, this is Bram’s code, I’m just seeing if I can help out :) I’m more confused now though…can you change your JSFiddle sample to only show the part that isn’t working for you?

If you mean you want to pass FontFaceObserver HTML, I don’t think that this would actually help in this situation…passing the Unicode character you’re checking for is already possible. The idea of the test string is if you need to, you can customise it and choose an appropriate test string for that particular font. Can you elaborate on why you’d like to use `` from the Unicode Private Use Area as the test string?

**Comment by gRoussac** [comment]
Hi,

Sure, thanks for any help.

http://jsfiddle.net/mgxzj987/20/ is only containing one test, failing on IE11, not Chrome. Please see enclosed screenshots. Even if I customize the string. 

 is &#57387;  in this font is the first icon you can see on the right corner of https://www.independer.nl/ header. 

I tried to test that as customized string, either in text, html version, unicode version.
https://www.utf8icons.com/character/57387/UTF-8-character and you can see in the fiddle rendered as an arrow. 
![arrow-e02b](https://user-images.githubusercontent.com/3099551/31010731-299279a8-a50c-11e7-927e-7f5577c6caa9.png)

![chrome](https://user-images.githubusercontent.com/3099551/31010762-3f13dde4-a50c-11e7-8c0a-67145b20cd08.png)
![ie11](https://user-images.githubusercontent.com/3099551/31010885-bd040eae-a50c-11e7-89eb-92a5c0da1455.png)
![ie112](https://user-images.githubusercontent.com/3099551/31010889-bee9603e-a50c-11e7-8f1d-12a12c47a196.png)

Regards

**Comment by bramstein** [comment]
This problem happens a lot with icon fonts. Because IE doesn't have a good way to detect a font is loaded it compares the width of a span containing test characters before and after loading a font. If the width changes it "detects" the font is loaded. It's not great, but it works with most fonts. Icon fonts are problematic because often the icons are designed on a square grid that matches the size of the "unknown" character in fallback fonts. So in this case the size of the icon and its fallback are the same and FFO fails to detect it loads.

You might be able to work around this problem by adding a couple non-square icons to your test string.
