### ISSUE TITLE
Publish source for fontfaceobserver.com?

### ISSUE THREAD

**Issue by papandreou** [bramstein/fontfaceobserver#112]
Hey Bram,

Hope you're doing well!

Since it was originally the font subset on fontfaceobserver.com that sparked my (and @Munter's) interest in automatic font subset generation, it could be fun to try it out as a test case to see if we can handle it, or if it has all been for nothin' :)

Would you be willing to publish the source, or at least share it with us?

--A

**Comment by bramstein** [comment]
Yea, I don't mind doing that. I'll need to revoke some AWS access keys first because I lazily committed them to the repository ;)
