### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by superpoincare** [bramstein/fontfaceobserver#113]
Hi Bram,

This is not an "issue", just a question. 

Can fontfaceobserver be used to detect emoji support?

**Comment by bramstein** [comment]
That should work, but you'll have to pass a custom test string to the `load` method (see the documentation).

**Comment by vijayaraghavanramanan** [comment]
Yeah understood. 

Was interested in this question since Wordpress uses canvas to detect emoji support and polyfills Twemoji if needed but privacy inclined browsers don't like accessing canvass. 

If it interests you: https://core.trac.wordpress.org/ticket/42428
