### ISSUE TITLE
When aria-hidden="true" elements have display: none !important; IE11

### ISSUE THREAD

**Issue by ikselll** [bramstein/fontfaceobserver#114]
## How to reproduce
Add CSS like this: `[aria-hidden] { display: none !important; }`
Can be reproduced in IE11.

## Effect
After 3000ms or custom set timeout font.load() promise is reject. It's because FontFaceObserver adding div with aria-hidden="true" and when with display none it isn't work.

## Proposition
Add some unique selector to this element, that it can be accessed and taken out from hidden elements.

**Comment by ogonkov** [comment]
It's out of the scope of font-observer, just don't change styles you didn't own.

I'm sure you need `display: none` for elements only inside some kind of wrapper of your site.
