### ISSUE TITLE
Load in a different window?

### ISSUE THREAD

**Issue by tolmasky** [bramstein/fontfaceobserver#116]
I'd like to load the font in a different iframe. Webfontloader provides a context parameter to supply a different window for doing the loading, does fontfaceobserver have any such ability? It's just a matter of using `theDocument` instead of the global `document` when creating dom elements, etc.

**Comment by codeclown** [comment]
Doesn't look like it's possible to override global `document`:

https://github.com/bramstein/fontfaceobserver/blob/6c0d945c15d3c3d624ff5ec53754e35bf1bb7661/src/observer.js#L200

**Comment by codeclown** [comment]
I needed this for a project so I made a fork. Here's a PR: https://github.com/bramstein/fontfaceobserver/pull/126
