### ISSUE TITLE
Add alternate build that uses callbacks (instead of Promises)

### ISSUE THREAD

**Issue by localnerve** [bramstein/fontfaceobserver#12]
Would you be open to a PR that adds a build that uses callbacks instead of Promises?
My motivation is that I want to use this in my first 14k, so I want this as small as possible.

**Comment by bramstein** [comment]
Hmm, that is an interesting question :smile: 

How would it work, an alternate build that uses callback with the primary option being promises?

**Comment by localnerve** [comment]
My simple, initial idea (untested) is that in "callback" builds, Observer.prototype.check just returns the promise executor directly, allowing the caller to supply callbacks for resolve, reject.

**Comment by bramstein** [comment]
I like that idea. The only downside is that FontFaceObserver can call `reject` or `resolve` multiple times. Promises take care of that transparently, but callbacks wouldn't.

**Comment by bramstein** [comment]
I gave this some more thought, and I think it makes sense to remove the dependency on promises. I think the benefits of a smaller size that can be inlined in the HTML document outweigh the benefits of promises. I'll change the API to only use callbacks (for those people who like promises it is very easy to convert).

**Comment by localnerve** [comment]
:+1:

**Comment by splintercode** [comment]
:+1:

**Comment by localnerve** [comment]
Is this planned for 2.x, per https://github.com/bramstein/fontfaceobserver/pull/19?

**Comment by bramstein** [comment]
Yes, it's on the schedule. Hope to get some work done on it next week (no promises though). Also, let me know if anyone else would like to take it on.

**Comment by bramstein** [comment]
Closing this and moving the discussion to #19.
