### ISSUE TITLE
Loading an entire font family

### ISSUE THREAD

**Issue by jessevdp** [bramstein/fontfaceobserver#120]
**Just to be clear—this is not a bug report or anything but just a *question*.** I just started using Font Face Observer. I have a question that I didn't find an answer to in the documentation. So here it goes.

---

When using Font Face Observer you can give the constructor an object to look for a specific font variant within the font family. Consider the following code snippet:

```js
const font = new FontFaceObserver('Family Name', {
  weight: 400,
  style: normal
})
```

If I omit this settings `Object` I would expect one of two things to happen. Either this `FontFaceObserver` now represents the entire font family (all the variants with the same `font-family` declared with `@font-face` rules) ***or*** the `FontFaceObserver` now represents just 1 variant within the family with defaulted values.

I noticed you can take an argument in the `.then` handler that will represent the loaded font. (Something that I couldn't find in the docs—I had to stumble upon that when experimenting.) Using this method I verified that my second theory was right: the object representing the font had defaulted values.

```js
{
  family: "Family Name",
  style: "normal",
  weight: "normal",
  stretch: "normal"
}
```

### **This leaves me wondering—is there a way to load all fonts of a specific family at once? Or do I need to specify every variant that I use?**

There is a reason as to why I want to load an entire family at once: When implementing some sort of FOUT behaviour I'm probably only going to swap out the fonts when all variants of a given family have loaded. I don't want the *regular* text to be in the fancy font but the *italic* text to be in a fallback font.

---

I know I can still achieve this behaviour by specifying al variants I want and putting them together in `Promise.all()`. It would just take away a lot of work if we could do this all with a single rule.

PS. This question might just turn into a feature request. 😉

**Comment by bramstein** [comment]
That's correct: if you don't specify any values it'll default them. I would have liked to load all the fonts in a family, but there isn't a reliable way to get that kind of information without either relying on the CSS font loading API (which this library polyfills), or going through the CSSOM. Both options aren't great, so for now, it is only for loading single font faces.
