### ISSUE TITLE
What happens if I call .load() multiple times for the same font?

### ISSUE THREAD

**Issue by johndubya** [bramstein/fontfaceobserver#124]
Because reasons, our code will at times call `.load()` multiple times for the same font. How does the plugin handle that situation?

Will it try to load the font multiple times, with each subsequent call attempting to download the font again?

Or will all the calls stack up while only downloading the font one time, then all resolve immediately afterward?

Or do any `.load()` calls after the first get ignored or dropped?

Thanks for any insight you can provide.

**Comment by Xdudu** [comment]
Hi, I'm curious on this topic too, so I look into the source code and find the author uses [`CSS Font Loading API`](https://github.com/bramstein/fontfaceobserver/blob/6c0d945c15d3c3d624ff5ec53754e35bf1bb7661/src/observer.js#L200) inherently, which means it will do nothing if fonts are already loading or loaded according to [this](https://www.w3.org/TR/css-font-loading-3/#font-face-load).

Hope it will be helpful ;)

**Comment by johndubya** [comment]
@Xdudu, sounds good, thanks!
