### ISSUE TITLE
Promise always rejected on latest Safari  (macOS and iOS)

### ISSUE THREAD

**Issue by nelsonvassalo** [bramstein/fontfaceobserver#131]
No matter how big I set the timeout to be, my Promise is immediately triggered as failed on both browsers.

Doesn't happen in any other browsers, any clue?

Thanks

**Comment by nelsonvassalo** [comment]
I've solved this: a single `font-style: italic`in the css file was making the call fail. Even though it is declared as a different family. This will constitute a bug no?

**Comment by bramstein** [comment]
That sounds strange. Do you have an example I can take a look at?

**Comment by iamskok** [comment]
> I've solved this: a single `font-style: italic`in the css file was making the call fail. Even though it is declared as a different family. This will constitute a bug no?

I'm also experiencing the same issue. What did you end up doing (hoping you haven't removed all `italic`s 😅 )?
