### ISSUE TITLE
Do you guys have Metrics ?

### ISSUE THREAD

**Issue by alejandrolechuga** [bramstein/fontfaceobserver#136]
>  Unlike the Web Font Loader Font Face Observer uses scroll events to detect font loads efficiently and with minimum overhead

I'm interested in using this library but I'd like to know how is Web Font Loader slower compared to this library do you guys have any metrics I can look ? and why is minimum overhead ?
The reason why this is a concern to me is because the web environment I'm using is limited in memory and cpu.

**Comment by bramstein** [comment]
I have done manual testing, but nothing official. It should be fast on modern browsers as it will use the native font loading API. On older browsers it should be faster than the Web Font Loader.
