### ISSUE TITLE
fontfaceobserver cause error

### ISSUE THREAD

**Issue by yangbinlovegis** [bramstein/fontfaceobserver#138]
![image](https://user-images.githubusercontent.com/8787605/69112914-787feb00-0abc-11ea-9472-904c3b0358ff.png)

this is my code

![image](https://user-images.githubusercontent.com/8787605/69112967-94838c80-0abc-11ea-87bf-c0e1f4e3a3f2.png)

**Comment by lostrepo** [comment]
@yangbinlovegis
Set proper `Access-Control-Allow-Origin` to `*` on server to access iframe on localhost (right now you accessing `null` origin which is forbidden without allowing all origins).

It's not Font observer issue.
