### ISSUE TITLE
Please provide unminified version of the scripts

### ISSUE THREAD

**Issue by PeterMK85** [bramstein/fontfaceobserver#14]
Please make it optional to have a minification on the project, do not provide minified version of the scripts as only option.

**Comment by bramstein** [comment]
Thanks for the suggestion. This project uses Closure compiler, so the unminified source is not suitable for minification with other minifiers. If you are using Closure Compiler you should be able to use the files in `src` directly.

**Comment by backflip** [comment]
We currently have an issue where 2.0.6 triggers a `Maximum call stack size exceeded.` in Safari when we use it within a Webpack setup with the `UglifyJsPlugin` (and only with the dev tools opened).

If I change `compilation_level` in the Grunt config from `ADVANCED_OPTIMIZATIONS` to `SIMPLE_OPTIMIZATIONS`, it works fine. 2.0.5 works fine, too.

**Comment by bramstein** [comment]
@backflip Do you have an example site? Can't think of anything that went into 2.0.6 that could cause that.

**Comment by backflip** [comment]
Seems to be an edge case of putting already minified code through UglifyJs. So it's probably independent of what really changed in 2.0.6 but rather a side effect of the new Closure Compiler output. I will check whether I can create a reduced test case.

**Comment by backflip** [comment]
Here you go: https://github.com/unic/fontfaceobserver-uglifyjs-demo

Apparently, specific `mangle` options are necessary to trigger the issue.

**Comment by backflip** [comment]
@bramstein Would it be an option to provide two dist version (one simply bundled and the other minified)? I agree this is a very weird edge-case, but there might be others.
