### ISSUE TITLE
fontfaceobserver.min.js flagged as Miner.Jswebcoin virus by Symantec

### ISSUE THREAD

**Issue by minusdavid** [bramstein/fontfaceobserver#143]
It appears that fontfaceobserver.min.js is getting flagged as the Miner.Jswebcoin virus by Symantec Endpoint Protection. 

It says that Symantec have had it flagged for more than 1 year, and that the file is untrustworthy.

I have examined the Javascript, and it really appears to be a false positive, but I'm noting it here anyway.

I'm going to look at remove use of fontfaceobserver for the time being though, so that my applications pass security screening.

**Comment by LeftCoastBC** [comment]
Our Symantec also flagged this file and quarantined it.

**Comment by pjconnors** [comment]
I started seeing this yesterday myself, and found it only flagging version 2.0.13.

It's also only happening (to me) in the version with the polyfill, and not fontfaceobserver.standalone.js, so perhaps there is something in the polyfill that is causing the false-positive detection.

**Comment by minusdavid** [comment]
Thanks for the comments, folks!

We're using fontfaceobserver.min.js v2.0.13 with the polyfill. 

Checking in with staff to see if Symantec have replied about the false-positive.

**Comment by minusdavid** [comment]
Could people submit a false positive report if they haven't already?

https://symsubmit.symantec.com/

**Comment by minusdavid** [comment]
Symantec have contacted me to say that they've verified that it is a false positive, and that the updated list is available via Rapid Release sequence >= 206799.
