### ISSUE TITLE
Unable to load custom font

### ISSUE THREAD

**Issue by z1haze** [bramstein/fontfaceobserver#144]
I have a custom font, which I am unable to load via FontFaceObserver. The font renders correctly in the browser and can be used, but it will not load with this library. Screenshot shows all glyphs included in the font, which should be enough to load, according to the docs:

![image](https://user-images.githubusercontent.com/6024725/85590902-a81a4700-b5f9-11ea-8bf1-99d98c0be89b.png)

**Comment by bramstein** [comment]
You may need to pass a custom test string if the font doesn't contain the characters mentioned in the README. Otherwise the load detection doesn't work on older browsers.
