### ISSUE TITLE
Consistently failing to load in macOS Safari when observing Cloud Typography webfont

### ISSUE THREAD

**Issue by reneruiz** [bramstein/fontfaceobserver#148]
Console: `Error: 3000ms timeout exceeded`

So I think I've isolated the issue to Cloud Typography's redirecting Safari to this file: https://d21kospbv2w2yj.cloudfront.net/fonts/640252/BE874059A30A61AEB.css

The error is still present if I bypass the redirect and go straight to that file. I also tried a different file that uses WOFF2 encoding vs legacy WOFF found in BE87….css

fontfaceobserver seems to handle this WOFF2 version just fine: https://d21kospbv2w2yj.cloudfront.net/fonts/640252/7EBEA322713F82A85.css

Sample of how I am observing typeface:

```
Promise.all([
    new FontFaceObserver('Gotham A').load(),
    new FontFaceObserver('Gotham B').load(),
]).then(() => {
    document.documentElement.classList.add('fonts-ready');
    document.documentElement.classList.remove('fonts-loading');
});
```

Not sure what it is about the WOFF version that is causing issues. Any ideas?

**Comment by rungta** [comment]
This issue can get resolved if [Cloud Typography](typography.com) served Safari users WOFF2 versions instead of WOFF versions of their fonts. I’ve reached out to their support. 🤞
