### ISSUE TITLE
Error on iPad Air, HTC One ["Error: Can't find variable: Promise\na@..."]

### ISSUE THREAD

**Issue by PeterMK85** [bramstein/fontfaceobserver#15]
I'm using the plugin in this enviroment:

    "angular": "1.2.15",
    "jquery": "1.10.2",
    "fontfaceobserver": "~1.4.5"

On Desktop: Chrome (41&44), FF, FF Dev works okay
On Mobile: Working okay on Nexus 4 (Chrome), Nexus 7II (Chrome)

Defect detected on iPad Air, HTC One, iPhone4, iPhone 5

Error message (in FF bug lite):

    Error: Can't find variable: Promise\na@.."aggregated script line here"

Which point to this line:

    z.prototype.a=function(a,b){var c=a||"BESbswy",C=b||3E3,h="font-style:"+this.style+";font-variant:"+this.variant+";font-weight:"+this.weight+";font-stretch:"+this.stretch+";font-feature-settings:"+this.featureSettings+";-moz-font-feature-settings:"+this.featureSettings+";-webkit-font-feature-settings:"+this.featureSettings+";",k=document.createElement("div"),l=new v(c),m=new v(c),n=new v(c),d=-1,e=-1,f=-1,q=-1,r=-1,t=-1,p=this;return new Promise(function(a,b){function c(){null!==k.parentNode&&document.body.removeChild(k)}

Where the context is:

    new Promise

And in the aggregated script I can't see Promise promise definition itself.

**Comment by bramstein** [comment]
It looks like those browsers do not have a native Promise implementation. You should either use a polyfill (like https://github.com/bramstein/promis) or the `fontfaceobserver.standalone.js` file which includes a Promise polyfill.
