### ISSUE TITLE
How do I load fonts from fontshare.com

### ISSUE THREAD

**Issue by ankitjena** [bramstein/fontfaceobserver#153]
## Description
I want to load a font from fontshare.com, I tried the same way as I load a google font using FontFaceObserver but that doesn't work. I even dowloaded the font and tried to load it but it seems I am doing something wrong. I am using NextJS and this is url of the font I am trying to load
https://api.fontshare.com/css?f[]=clash-display@400,700&display=swap

Can anyone help me out. Thanks in advance.

**Comment by rahulgajjar** [comment]
Please follow the instructions on the font download page on fontshare.com

Copy the code below to <head> of your HTML file

`<link href="https://api.fontshare.com/css?f[]=clash-display@400,700&display=swap" rel="stylesheet">`

And include these CSS rules

`font-family: 'Clash Display', sans-serif;`
