### ISSUE TITLE
Font load not detected depending on check() test string

### ISSUE THREAD

**Issue by chrissam42** [bramstein/fontfaceobserver#17]
I'm having some trouble detecting load of the [Interstate Pi](http://www.fontbureau.com/fonts/InterstatePi/) fonts from Font Bureau. They have really bizarre character sets with very spotty coverage of the alphabet. 

It seems that the load detection is very sensitive to the test string provided to `check()`. If font doesn't contain some of the test chars, its load tends to not get detected. However I've found that even in many "normal" fonts, if you set the string to something like "abdef" many fonts won't be detected with that either.

Do you have any recommendations for what kinds of test strings are most effective? I assume a mix of widths and perhaps some kerning pairs would usually be effective.

**Comment by bramstein** [comment]
Thanks for the report. We've had good results with the default test string `BESbswy`. If the font is metric compatible with the fallback fonts it becomes harder to detect (though I've only seen a handful cases like this). Could you list a couple of fonts that are having difficulty with "abdef"? That sounds worth looking into. 

I can see why Interstate PI might be troublesome. What unicode code points are those glyphs mapped to? As long as the default fallback for that code point has a very different width it should work.

**Comment by chrissam42** [comment]
I work for Font Bureau, and I haven't been able to find anyone who knows of an official charset listing for these fonts! So I had to pull them out of the fonts themselves.

Ignoring punctuation, these are the charsets for Interstate Pi:

* One: BDEFGHILNOPQRUZ0123456789abcdefghijklmnopqrstuvwxyz
* Two: FGHJ0123456789abdefghijklmnopqrstuwxyz
* Three: CDEGHJKOPRXZ0123456789abcdefghijklmnopqrstuvwxyz
* Four: Z0123456789abcdefghijklmnopqrstuvwxyz

You can see what I'm talking about. There's no set of capital letters that is in all four!

When I tried "abdef", Interstate Pi One loaded but the other three didn't.

Thanks for reminding me about the fallbacks, I had totally forgotten to set those smartly. I'll let you know what I find.

**Comment by bramstein** [comment]
Let me know how it goes. Interstate Pi does not appear to be on Webtype, so short of buying the typeface it is difficult for me to test :)

**Comment by chrissam42** [comment]
Tried it with Adobe Blank fallback and still no love. Incidently, this is BESbswy in IP One:
![image](https://cloud.githubusercontent.com/assets/587009/7339123/0fd904aa-ec31-11e4-83e2-d524f6da83f8.png)

Obviously the Pi metrics should not have a problem being confused with any standard font. I can send you a copy if you want to experiment on it.

**Comment by bramstein** [comment]
That would be great, thanks!

**Comment by chrissam42** [comment]
I have had better luck with the string "aeiou" — so this is not the end of the world, but I am still curious why missing characters in the font seems to kill it.

**Comment by chrissam42** [comment]
I must not have cleared my cache or something, because the fonts I thought weren't loading now do. So when used as designed, with a test stein that is well supported by the font in question, it seems to be reliable. Sorry to bother you.
