### ISSUE TITLE
Option for timeout

### ISSUE THREAD

**Issue by yoyurec** [bramstein/fontfaceobserver#2]
Add possibility to set timeout...

this one? https://github.com/bramstein/fontfaceobserver/blob/master/src/observer.js#L58

For example on heavy pages on slow connection (you can emulate it with chrome) 2G (3G, for example is OK)  you will never see styled text (((

![screenshot 19 02 15 17 29 56](https://cloud.githubusercontent.com/assets/137919/6269628/19cca438-b85d-11e4-97c8-af8115262a51.png)

**Comment by bramstein** [comment]
This has been added per v1.4.0. Thanks for the suggestion!

**Comment by yoyurec** [comment]
any tips/docs for usage options?
