### ISSUE TITLE
body may not be parent element at removal time

### ISSUE THREAD

**Issue by BradleyStaples** [bramstein/fontfaceobserver#20]
Just ran into an issue where this script combined with an offCanvasMenu (hamburger menu) script caused the <body> to NOT be the parent when it came time to remove the child node, so it errors out on

    null !== k.parentNode && document.body.removeChild(k)

Changing it to be this seems to fix it for my case but I didn't do any real testing to confirm there weren't other issue at play. 

    null !== k.parentNode && k.parentNode.removeChild(k)

**Comment by BradleyStaples** [comment]
submitted pull request #21 once I got home for this issue.

**Comment by bramstein** [comment]
This has been fixed in v1.4.8. Thanks!
