### ISSUE TITLE
Font Detection When Default Fonts are Styled? 

### ISSUE THREAD

**Issue by stephenhmarsh** [bramstein/fontfaceobserver#25]
This might be a dumb question but... 

We are considering styling system/fallback fonts so that they take up the same visual space as our web fonts, so that when the web fonts finally load there is minimal (or no) page jump.  Given that Font Face Observer (and other font-event polyfills) detect loading by measuring two DOM elements for different sizes, will the detection still be accurate if we style our fallback fonts for matching geometry with webfonts?

**Comment by bramstein** [comment]
Great question! Font Face Observer will apply its own styling to its detection DOM elements so you should be able to style your fallback fonts independently.

**Comment by stephenhmarsh** [comment]
👍 
thanks for this project
