### ISSUE TITLE
iOS 7 JS Error when using `fontfaceobserver.js` v1.4.9

### ISSUE THREAD

**Issue by francoismassart** [bramstein/fontfaceobserver#26]
I did use `fontfaceobserver.js` v1.4.9 and it worked fine but when I tested my page on my iPhone running iOS 7.1 I did get this error in Mobile Safari:

**[Error] TypeError: 'undefined' is not an object (evaluating 'w.Promise.all')**

When testing with another iPhone running iOS 8, it worked fine.

I was able to make it work in iOS 7 too by using `fontfaceobserver.standalone.js` v1.4.7 but is it normal ?

What is the difference between the regular and the standalone version ?
I get the idea that there is some extra code in the standalone, but what is its purpose and when should we use which version ?

Thank you for this cool script :)

**Comment by bramstein** [comment]
The difference is that the standalone version includes a polyfill for promises. If the browsers you target doesn't need a polyfill or if you already have one you don't need it. This caused more confusion, so I decided to always add the polyfill. If you upgrade to the latest version this problem should be gone.
