### ISSUE TITLE
Provide a non-minified version of the library

### ISSUE THREAD

**Issue by dlee** [bramstein/fontfaceobserver#3]
Right now, `fontfaceobserver.standalone.js` and `fontfaceobserver.js` are minified.

It would be preferable if those were not minified, and separate minified version was provided (i.e. `fontfaceobserver.standalone.min.js`).

**Comment by bramstein** [comment]
Out of curiosity, what would you do with it?

**Comment by dlee** [comment]
It's so that we can include it into our own assets directory, which would show the unminified version during development (for debugging purposes) and minify it for production.

**Comment by bramstein** [comment]
You can build a debug version with `grunt debug`, but I'm not sure how useful it would be.

**Comment by yoyurec** [comment]
+1
almost every git repo uses 2 versions...

and it's easier to read - for example i can fast look at sources on git to find bug solution and post link to target string in opened issue
