### ISSUE TITLE
fontfaceobserver and arabic fonts

### ISSUE THREAD

**Issue by miguelpedregosa** [bramstein/fontfaceobserver#31]
I am implementing fontfaceobserver in a website with custom Arabic fonts and doesn't work properly, always call the failure part of the promise.

So, I'm using an Arabic string pasted in the source and a string in Unicode notation as string in the check function . Also tried with ASCII string.

For test, I downloaded the source code of fontfaceobserver and a couple of fonts from https://github.com/misamplus/dinky-theme/tree/master/font and ran the testsuite (modifying the first family font test with an arabic font like BMitra Regular). Console displays: Uncaught (in promise) Error: 
expected 301 not to equal 301

Thank you for your help.

**Comment by bramstein** [comment]
By default FontFaceObserver can only detect fonts that have some ASCII characters. These fonts only contain Arabic, so they are not detected. You can change FontFaceObserver's default test string to contain Arabic and then it should detect the load correctly.

For example, the following would work:

```
      font.check('\u0643').then(function () {
        console.log('loaded');
      }).catch(function () {
        console.log('failed');
      });
```
