### ISSUE TITLE
Provide the cache ttl for the font file

### ISSUE THREAD

**Issue by mikeytown2** [bramstein/fontfaceobserver#33]
I'm currently using a cookie to say when the font has been downloaded. If the cookie could be set to the Expires header from the downloaded font that would be nice.

**Comment by bramstein** [comment]
Font Face Observer uses the browser to download the font, so it doesn't have access to HTTP headers. I  started using `sessionStorage` instead of a cookie. It'll clear after each session (so you'll see FOUT/FOIT once per session), but not during a session.

**Comment by mikeytown2** [comment]
Would a new request to the font file via javascritp use the browser cache or would it create a new connection? http://stackoverflow.com/questions/24943922/is-there-a-way-to-use-browser-cache-for-angularjs-json-requests-http-resource http://stackoverflow.com/questions/220231/accessing-the-web-pages-http-headers-in-javascript

**Comment by bramstein** [comment]
It would come from the cache, but should still have the correct headers.
