### ISSUE TITLE
Is there an issue with icon fonts ?

### ISSUE THREAD

**Issue by QuentinFchx** [bramstein/fontfaceobserver#34]
I tried to use this library to detect if an icon font is available. (ie: [Font Awesome](https://fortawesome.github.io/Font-Awesome/))
The following check always failed, even if the font is properly loaded (I can see the icons):
`var fontAwesomeObserver = new FontFaceObserver('FontAwesome', {});`

I think this is because icon fonts are using Unicode code points through the `content` css property, and I did not manage to detect them with this library. I tried with [String.fromCodePoint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint), [String.fromCharCode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode).

These Unicode points are subject to change and it would not be "wise" to rely on them.
Icon fonts use class names to specify icons, do you think we could adapt the library to accept class names as `testString` ?

**Comment by bramstein** [comment]
Icon fonts should work (though I'm generally not that excited about icon fonts). Do you have a sample page somewhere?

**Comment by QuentinFchx** [comment]
I think this fiddle is reproducing properly the issue. https://jsfiddle.net/86crhscq/1/

**Comment by bramstein** [comment]
You need to specify some unicode code points for the font load detection to work. For example:

https://jsfiddle.net/pncgmqt2/

I have no plans to add support for a class as test string (unicode code points to glyph mappings don't often change in fonts, so I don't think this is worth adding).

**Comment by QuentinFchx** [comment]
Ah thank you, I did not manage to make it work with unicode code points in the first place.
Yeah, my main concern was about changes in the mapping but I think it's easily fixable!

**Comment by RobbertWolfs** [comment]
@bramstein  

Any updates about this?

the `fontFaceObserver.check` method does not work anymore in a newer version?

**Comment by kennethormandy** [comment]
@RobbertWolfs The API changed from `check` to `load` in v2.x, and if I remember correct it is identical otherwise. Here’s a fixed version of that sample for you: https://jsfiddle.net/1wuxbf4h/

The relevant example from the README is:

> If your font doesn't contain at least the latin "BESbwy" characters you must pass a custom test string to the `load` method.
> 
> ```js
> var font = new FontFaceObserver('My Family');
> 
> font.load('中国').then(function () {
>   console.log('Font is available');
> }, function () {
>   console.log('Font is not available');
> });
> ```
