### ISSUE TITLE
weight not taken into account in success of Promise

### ISSUE THREAD

**Issue by yvanavermaet** [bramstein/fontfaceobserver#38]
Hi

We have an issue and we're thinking it might be a fontfaceobserver bug.

    var adelle, adellebold;
    
    adelle = new FontFaceObserver('adelle sans', {
    	'weight': 'normal'
    });
    
    adellebold = new FontFaceObserver('adelle sans', {
    	'weight': 'bold'
    });
    
    adelle.check().then(function() {
    	htmlElement.className += ' adelle-loaded';
    });
    
    adellebold.check().then(function() {
    	htmlElement.className += ' adelle-bold-loaded';
    });

In the CSS we have the following: 

    @font-face {
    	font-family: 'adelle sans';
    	src: url($font-path + 'adellesans-bold-webfont.eot?c=' + $fingerprint);
    	src: url($font-path + 'adellesans-bold-webfont.eot?#iefix&c=' + $fingerprint) format('embedded-opentype'),
    		 url($font-path + 'adellesans-bold-webfont.woff2?c=' + $fingerprint) format('woff2'),
    		 url($font-path + 'adellesans-bold-webfont.woff?c=' + $fingerprint) format('woff'),
    		 url($font-path + 'adellesans-bold-webfont.ttf?c=' + $fingerprint) format('truetype'),
    		 url($font-path + 'adellesans-bold-webfont.svg#adelle_sansbold?c=' + $fingerprint) format('svg');
    	font-weight: bold;
    	font-style: normal;
    	font-stretch: normal;
    }

    @font-face {
    	font-family: 'adelle sans';
    	src: url($font-path + 'adellesans-regular-webfont.eot?c=' + $fingerprint);
    	src: url($font-path + 'adellesans-regular-webfont.eot?#iefix&c=' + $fingerprint) format('embedded-opentype'),
    		 url($font-path + 'adellesans-regular-webfont.woff2?c=' + $fingerprint) format('woff2'),
    		 url($font-path + 'adellesans-regular-webfont.woff?c=' + $fingerprint) format('woff'),
    		 url($font-path + 'adellesans-regular-webfont.ttf?c=' + $fingerprint) format('truetype'),
    		 url($font-path + 'adellesans-regular-webfont.svg#adelle_sansregular?c=' + $fingerprint) format('svg');
    	font-weight: normal;
    	font-style: normal;
    	font-stretch: normal;
    }

To test if the classes actually work, we removed the first font-face (the bold one).

The expected result is that the promise of adellebold is NOT executed and that there is no adelle-bold-loaded class on the html-element.
However, the actual result is that the promise is executed and therefor the css-class is added.

Is this a bug with fontfaceobeserver or are we using/doing it wrong?

Thanks in advance!

Kind regards,
Yannick

**Comment by bramstein** [comment]
Sorry for the late response on this. This is the result of the font matching algorithm in browsers. If a font family has the same name but a different weight, it'll still match because the browser considers it "close enough" and will apply the font. Unfortunately, there is no way for Font Face Observer to detect this condition. I personally think the font matching algorithm should be changed, but that's going to be an uphill battle.

As a workaround, you could give the font families unique names, such as `adelle sans regular` and `adelle sans bold`.

**Comment by Bnaya** [comment]
Is this behavior is part of the spec?

**Comment by bramstein** [comment]
@Bnaya This behaviour is part of the CSS spec. The same applies for the Web Font Loader.
