### ISSUE TITLE
Prefetch and slow connections causes `Uncaught (in promise)` / promise rejected error

### ISSUE THREAD

**Issue by robwierzbowski** [bramstein/fontfaceobserver#39]
If I prefetch fonts:

```html
<link rel="prefetch" href="fonts/charter-bt-roman.woff2">
<link rel="prefetch" href="fonts/charter-bt-italic.woff2">
```

And observe them with FFO:

```js
let fontObservers = [
  new FontFaceObserver('Charter BT').check(),
  new FontFaceObserver('Charter BT', {style: 'italic'}).check()
];

Promise.all(fontObservers).then(function() {
  document.documentElement.classList.add('is-fontsLoaded');
});
```

*and* slow my connection (regular 2g with Chrome Dev Tools):

**Expected outcome**: It takes a while but my fonts load.
**Actual**: I get the error `Uncaught (in promise)`. If I return the `all` promise, the values are `Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: z}`.

The odd thing is this works fine if I'm throttling to a slightly faster value, even regular 3g. Let me know if you need any more info, or have ideas.

**Comment by robwierzbowski** [comment]
Could this have something to do with the font already being loaded when FFO is called?

**Comment by bramstein** [comment]
I think this is probably related to the timeout value. If the fonts take more than 3 seconds to load Font Face Observer will consider them failed. You can increase this time by passing a larger value (e.g. `5000` for 5 seconds) as the second parameter to the check function.

**Comment by robwierzbowski** [comment]
Ah, probably. Somehow I missed that in the docs. Thanks, and closed.
