### ISSUE TITLE
Avoid horizontal scrolls

### ISSUE THREAD

**Issue by yoyurec** [bramstein/fontfaceobserver#4]
on mobile devices (iPhone6 for ex.) while page loads i see annoying horizontal scroll few seconds.
it brake page layout (((
i know that you are using some technic (any detailed description?) with scroll events, but how it can be fixed?
element that blow column is:
```
<span style="display: inline-block; position: absolute; height: 100%; width: 100%; overflow: scroll;">
    <span style="display: inline-block; width: 200%; height: 200%;"></span>
</span>
```

**Comment by yoyurec** [comment]
looks like you just need add position to elements here
https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js#L14
`                'left:0;' +
`

**Comment by yoyurec** [comment]
can you plz explain how https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js works and why all this elements https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js#L36-L40

**Comment by yoyurec** [comment]
i've added PR, but maybe it's better to review all styles and/or reuse those: https://github.com/zachleat/fontfaceonload/blob/master/src/fontfaceonload.js#L25-L38

**Comment by bramstein** [comment]
I've changed the code to use the same method as the Web Font Loader. I still like to explore other ways of hiding the text, but this should avoid most cases where scroll bars are shown.

**Comment by yoyurec** [comment]
> I still like to explore other ways
maybe this (not tested, jusrt thoughts that -99999(9)px **<** -100%)?
```
left: -100%;
top: -100%;
```
