### ISSUE TITLE
RTL languages don't detect properly

### ISSUE THREAD

**Issue by craftyInstigator** [bramstein/fontfaceobserver#42]
When detecting fonts with dir="rtl" at the top level the detection fails. Adding dir="ltr" to the detection div element resolves the problem.

**Comment by bramstein** [comment]
That's interesting. I haven't tested with RTL languages. Do you have an example so I can reproduce the bug? Thanks!

**Comment by craftyInstigator** [comment]
Here is a slight, simple modification of a previously working example:
https://jsfiddle.net/pncgmqt2/2/
I simply added dir="rtl" to the body tag to break detection.

**Comment by bramstein** [comment]
Thanks a lot for the test case. This is fixed in v1.5.5.
