### ISSUE TITLE
Can we use different type of fonts, or just one?

### ISSUE THREAD

**Issue by niceoutput** [bramstein/fontfaceobserver#44]
In your examples you just mentioned one font-family. Could we use more font-family with this script?

Thanks

**Comment by bramstein** [comment]
Yes, you can load multiple fonts. You just need to create multiple FontFaceObserver instances for each font. For example:

```
var font1 = new FontFaceObserver('Family A');
var font2 = new FontFaceObserver('Family B');

Promise.all([font1.check(), font2.check()]).then(function () {
  console.log('Family A & B have loaded');
});
```
