### ISSUE TITLE
Broken export in 1.6.1

### ISSUE THREAD

**Issue by tvararu** [bramstein/fontfaceobserver#46]
It looks like you [updated the module](https://github.com/bramstein/fontfaceobserver/commit/af0691d43de8c099958ea4252e78d8aa69a47919) to now correctly export the object in the canonical node package way. However, this is a breaking change, and the new version number does not reflect this. It should be `2.0.0`.

I suggest you address this by adding back the old method of export, adding a `console.warn` clause when it is in use (rather than the new common.js one) that this method of using the package is now deprecated, and releasing this version as `1.6.2`.

**Comment by bramstein** [comment]
Just so I understand the issue: you were using FontFaceObserver as a module and relied on its constructor being in the global window? Your suggestions is to, in addition to the module export, assign the constructor to the global window?

**Comment by tvararu** [comment]
Yes. That would not break backwards compatibility.

Here is a diff of the (coffeescript) commit that fixed our application, which was breaking earlier with v1.6.1:

```diff
-    require('fontfaceobserver') // global
+    var FontFaceObserver = require('fontfaceobserver')
```

**Comment by bramstein** [comment]
I think that's a good point, I'll fix it. I just realised the commonjs package doesn't include the Promise polyfill by default either (I assumed most people would want to include that separately --- or use a different library).

**Comment by mathisonian** [comment]
:+1: for this. I ran into the same problem with the minor version upgrade breaking a build. @tvararu's suggestions make sense to me

**Comment by bramstein** [comment]
Thanks, it's in v1.6.2 now. Let me know if you run into any problems.

**Comment by tvararu** [comment]
Thanks a lot! :raised_hands:
