### ISSUE TITLE
IE9 Not Working

### ISSUE THREAD

**Issue by extractachris** [bramstein/fontfaceobserver#48]
I am using `1.6.1` of `fontfaceobserver.js` with the included polyfill.

Works just fine in IE10 & IE11, however, it does not seem to work in IE9:

```
var fontObservers = [];

var fontFamilies = {
  'Univers LT W01_55 Roman1475956': [
    {
      weight: 400
    }
  ]
}

Object.keys(fontFamilies).forEach(function(family) {
  fontObservers.push(fontFamilies[family].map(function(config) {
    return new FontFaceObserver(family, config).check()
  }));
});

Promise.all(fontObservers)
  .then(function() {
    document.documentElement.classList.add('fonts-loaded');
  }, function() {
    console.info('Web fonts could not be loaded in time. Falling back to system fonts.');
});
```

I receive no error or message in console whatsoever, nor is the `.fonts-loaded` class ever added to my `html` element.

**Comment by bramstein** [comment]
Do you have a test page somewhere so I can take a look? I tested v1.6.1 in IE9 and it is working.

**Comment by extractachris** [comment]
Here's a fiddle. Font loads / renders in IE10, but not IE9:

https://jsfiddle.net/kyzwjfw1/

**Comment by bramstein** [comment]
This is not an issue with FontFaceObserver, but with the code you've written inside the success handler:

```
document.documentElement.classList.add('fonts-loaded');
```

IE9 does not support classList, so you'll need to use something else (`className` for example). You can see an example here: https://jsfiddle.net/q435q6zz/3/

Thanks for reporting it though! :+1:

**Comment by extractachris** [comment]
:+1:
