### ISSUE TITLE
Observer check doesn't work in IE for some fonts (FontAwesome)

### ISSUE THREAD

**Issue by TheMadDeveloper** [bramstein/fontfaceobserver#50]
Though it hurts my soul to file an IE issue, I'm at a loss to find a fix and am not at liberty to turn my back on IE for this project.

I'm trying to use fontfaceobserver to detect when an icon font (i.e. [FontAwesome](https://fortawesome.github.io/Font-Awesome/)) is loaded--but it doesn't seem to work on IE browsers.  I have created the following fiddle to demonstrate my issue:

https://jsfiddle.net/TheMadDeveloper/15s03g3u/3/

**The promise returned by `check()` resolves properly for most browsers, but is rejected in IE**, after the timeout, even though the font loads before then.  I believe this is the case for all versions of IE, although IE10 was what I was using when I last tested.

I spent some time trying to trace down the issue, though I was working with the minified version because I clearly enjoy pain.  I followed the execution path to: `dom.waitForBody(function () { ... })`  I got a little confused around `var hidden = document['hidden'];` (which always seems to === `false` in IE).  Additionally, the `onResize()` callbacks on the rulers are never called.  So, ultimately, the actual `check()` function defined in that block around line 198 never gets called.

More FYIs:
* When I tried manually resizing the ruler elements after the page loaded (having prevented their removal), the ruler onResize listeners do get triggered.
* This might be font specific--I can't remember if it successfully worked for more standard fonts.
* Technically, I'm trying to make this work for a custom font, but FontAwesome seems to have the same issue.

**Comment by bramstein** [comment]
Thanks for filing this bug report and making a test case. I think I tracked the problem down. Font Face Observer uses the character you give it to determine if a page has loaded (in this case `\uF00C`). It does this by detecting a change in the width of the test characters when the font loads. Unfortunately the character you picked renders at exactly the same width as the default fallback for that character. The character is one 1em wide, and so is its fallback. This means that from the point of view of Font Face Observer the font never loads. You can prevent this by using multiple characters with different widths for test strings. Looking at FontAwesome, I would recommend: `\uf287\uf142\uf0fc `.

Let me know if that solves your issue.

**Comment by TheMadDeveloper** [comment]
Thank you for the quick response!  Using a character with a different width did fix my problem.  Fortunately, there was one character that was more than 1em in the custom font I'm trying to use, so easy fix.

**Comment by diniscorreia** [comment]
I just ran into this same issues. Unfortunately, I've tried a bunch of different characters from my custom icon font with no luck.

Any other ideas to solve this?
Thanks in advance!

**Comment by bramstein** [comment]
No, there's no other way to monitor a font load when the CSS font loading API is not available. My only recommendation is to not use an icon font. Sorry!

**Comment by diniscorreia** [comment]
Thanks! By the way - and this will be totally a type newbie question :) - is there any way to check the em width of the characters, just to see if I can think a different one? (or maybe set a different fallback font?)

**Comment by drpepper** [comment]
Hi, I'm coming to this issue quite late, but it helped getting FontFaceObserver to work on Edge with my icon font. 

Would it be possible to add it to the docs? I think it could help others.

Thanks for the great library!
