### ISSUE TITLE
Firefox Issues

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [bramstein/fontfaceobserver#53]
I am seeing some issues in Firefox. (Tested on Firefox 44). I have to put fontfaceobserver on top of everything (inline css, preload link etc ... ) to make it work. Other browsers work fine even if I put fontfaceobserver code below the inline css. 

I have also noticed the same in Firefox when I load google fonts using loadCSS. 

In both, fonts work on second load (as the fonts get loaded I supposed but fontfaceobserver doesn't run properly to set class to "fonts-loaded").

**Comment by bramstein** [comment]
Do you have a test page somewhere, so I can take a look? Thanks!

**Comment by vijayaraghavanramanan** [comment]
Dear @bramstein 

Sorry for the delay. My site is [here](www.concertedaction.com) 

I use loadCSS to load google fonts and style.css and set class to fonts-loaded

For second load I use sessionstorage which quickly sets the html class to fonts-loaded. 

Try loading it with Firefox multiple times after clearing the cache. It's because it sometimes works and sometimes doesn't. 

Thanks.

**Comment by vijayaraghavanramanan** [comment]
It's possible it has to do something with Unicode range which both Google Fonts and Firefox now supports. 

Attached two screenshots. 

In the first, fonts are loaded (but not all) and fonts displayed are Arial. 

In  second screenshot, two additional fonts are loaded and the site displays Open Sans. 

![unicode 1](https://cloud.githubusercontent.com/assets/13736892/13092790/dde713b6-d527-11e5-8d2a-98bbe17bd7a2.png)
![unicode 2](https://cloud.githubusercontent.com/assets/13736892/13092798/e2cc2786-d527-11e5-9ea0-59e3e8049f39.png)

**Comment by bramstein** [comment]
Hey, I tried for quite a while, but I didn't manage to reproduce the problem (Firefox 45, OS X). Is this issue related to a particular version of Firefox or OS?

**Comment by vijayaraghavanramanan** [comment]
Thanks. 

I am using Firefox 44. Latest stable on Windows. I also checked 45 Beta on both Windows and OS X using Browserstack. 

Firefox 45 OS X seems to be working fine not Windows.

**Comment by vijayaraghavanramanan** [comment]
Could be a Firefox bug. I am not getting this in Firefox Nightly 47.0a1 on Windows but getting the unexpected behaviour in FF 44.0.2/Windows.

**Comment by vijayaraghavanramanan** [comment]
Bram,

Did you have a chance to look at it?

I used uglfyjs2 to just check for errors (I know your code is already minified but I was just checking for any message) and it says 

symbol b is defined but not referenced. 

Is that something to worry?

But as I mentioned, the code seems to work with Firefox Nightly in Windows so it's probably a bug in Firefox. At any rate, loadCSS has some issues in Firefox 38 (which is popular with organizations) 

https://github.com/filamentgroup/loadCSS/issues/134

So I am thinking of blocking render for Firefox - do you know of a simple way to do it?

**Comment by vijayaraghavanramanan** [comment]
1.6.5 seems to solve this. No issues on Firefox 44.0.2 on Windows. 

Will close this issue in a day after confirming/testing.  

By the way I am getting a Chrome FOIT. But only for a few elements. Could be a Chrome bug. 

There is a Chrome bug I raised (not related to Fontfaceobserver) but it might be causing it. 

https://bugs.chromium.org/p/chromium/issues/detail?id=579912

But from your experience, any reason this might happen, ie FOIT on Chrome despite using FF Observer?

**Comment by vijayaraghavanramanan** [comment]
I am still getting the error on FF44 and FF45beta. But not on Firefox Nightly. 

So I have reported it as a bug at Mozilla: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1253861

**Comment by vijayaraghavanramanan** [comment]
I see this error on Firebug. Is it related to any of the above issue in Firefox?
![document-fonts](https://cloud.githubusercontent.com/assets/13736892/13640249/e33e9f14-e639-11e5-8286-3124329667ea.png)

**Comment by vijayaraghavanramanan** [comment]
Apologies for multiples posts. I tried it on Browserstack/Windows 10/Firefox 44. 

I get this error message: 
![untitled picture](https://cloud.githubusercontent.com/assets/13736892/13642424/6e9df5de-e642-11e5-9b00-79451993d503.png)

The website referred in that message is: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm

which says use DOM.promise instead.

**Comment by bramstein** [comment]
Is this still an issue? Sadly, I haven't been able to reproduce it.

**Comment by vijayaraghavanramanan** [comment]
Not any longer. Can't figure if it's because of new version of Firefox or because I was doing something wrong. Anyway you can close this.
