### ISSUE TITLE
Non minified version

### ISSUE THREAD

**Issue by frontEndWebDev** [bramstein/fontfaceobserver#54]
Hi, thank you for amazing work on this project :) . Please add non minified version of fontfaceobserver for Bower. It would really be helpful for those who are working with requirejs / amd.

**Comment by bramstein** [comment]
Hey, this project is using Closure Compiler and non-minified versions aren't that useful (since they require the whole Closure compiler setup). They simply won't work. I could add a debug version, but that'll have mangled variable names which makes debugging hard.

**Comment by frontEndWebDev** [comment]
Ok, I will find workaround. Thanks :) .
