### ISSUE TITLE
Promise should resolve when font installed locally

### ISSUE THREAD

**Issue by jaicab** [bramstein/fontfaceobserver#55]
Hi @bramstein,

As a performance improvement, FontFaceObserver should include a way of testing if a font is installed locally and then resolve the Promise if given the case before using the font loading API.

I've put together a minimal demo to test/reproduce the scenario more easily. It's testing Arial at the moment.
https://jsbin.com/cogipa/edit?html,js,console

Oddly enough it does resolve on Safari OSX 9.0.3.

**EDIT:** This variation of FontFaceObserver is to live as a parallel version of it with this extra feature.

Thanks

**Comment by jaicab** [comment]
I'll be doing some tests over on my forked version, I'm going for the "compare against Comic Sans, expect different width" way of implementing this. Unless you think there's a better way.

**Comment by PeterMK85** [comment]
@jaicab 

How can you check if that font is _exactly_ the same? (for ex.  name can be the same but the subset can be different, or basically a different font type /condensed/ under the same name)

**Comment by vijayaraghavanramanan** [comment]
It's for the same reason Paul Irish introduced the smiley variation in the local reference in the "bullet proof" @font-face syntax. 

http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/

**Comment by jaicab** [comment]
@PeterMK85 
If the name and style matches a font installed locally, the browser will pick that one and ignore (and therefore never load) the one served via `@font-face` anyway, no matter what font-loading solution you use.

So detecting if a font has a local match will only skip the font loading API process and resolve the Promise but the result would be the same that is now, when using a locally installed font as a primary choice on a font-family list.

I guess that if you want to avoid this problem at all times you should always rename your fonts so the family name never matches a locally installed font.

**Comment by jaicab** [comment]
Thanks @vijayaraghavanramanan, that explains the __why__ better.

Also @PeterMK85, the idea behind this is to allow FontFaceObserver to use a local font if there's a match and never download the external font files, therefore improving performance. 
If I had to compare both the local and the external (which theoretically could be done) I would need to download the external one anyway, making this a futility as you can always use the current implementation.

And I'm not suggesting to add this to FontFaceObserver as its function is targeted to use the font loading API (as @bramstein mentioned on #8), but as a separate parallel version.

**Comment by bramstein** [comment]
@jaicab If you're making a special build, it might be easiest to just set `Observer.SUPPORTS_NATIVE` to `false`. This will disable the native font loading and always use the old method (which supports detection of locally installed fonts).

Also, I would generally recommend against using locally installed fonts (even for performance reasons). You can read my reasoning here: http://bramstein.com/writing/web-font-anti-patterns-local-fonts.html

**Comment by jaicab** [comment]
@bramstein I did notice that the old method does something very similar to what I was implementing so yes, I'll use that.

Regarding wether or not using locally installed fonts is a good idea, I understand your concerns. I do think that using locally installed fonts can cause unexpected results, unless you know the font pretty well.
Although when using Google Fonts directly and not self-hosting them, the `local()` bit is specified, therefore there's no way to avoid this behavior, right?

So I'll be using another parameter in `check` to ignore `Observer.SUPPORTS_NATIVE` when `true`. This way we can target specific fonts for this test, but the default behavior remains as it is now.

**Comment by jaicab** [comment]
Ok @bramstein, I think this does the job!
https://github.com/jaicab/fontfaceobserver/blob/local-font/src/observer.js#L130

If you feel like you want this merged with FontFaceObserver or making it into a different file, I'm happy to do a PR. The current behavior remains untouched, so it's only optional, to me it seems like it should be on this repo, but maybe you don't as you don't recommend doing this? You tell me :)

Here's a demo: https://output.jsbin.com/yonopa/quiet

**Comment by bramstein** [comment]
@jaicab That looks right to me. I can be convinced otherwise, but I don't think this is a common enough use-case to support. I'd be happy to add a link to your fork if you're planning on maintaining it. Let me know!

**Comment by bcamper** [comment]
Hi, I have a case that I think is related (forgive me if not, I'm new to the world of fonts :)  I work on a [map rendering library](https://github.com/tangrams/tangram) that uses Canvas to draw map labels (via WebGL textures). The text style is user-specified, so the font families used are not known ahead of time, and can mix system fonts like Helvetica with custom fonts the user may have loaded in their own CSS.

I noticed that `FontFaceObserver.check()` was timing out on Helvetica, which surprised me (then I found this issue). Looking at the spec, it appears that [`document.fonts.check()`](https://drafts.csswg.org/css-font-loading/#font-face-set-check) includes checks for system fonts, and will return a boolean immediately (e.g. not a Promise). This behavior looks borne out in Chrome and FF: `document.fonts.load('16px Helvetica', 'abc')` resolves with an empty array, but `document.fonts.check('16px Helvetica', 'abc')` returns `true`.

Would an initial call to `check()`, before the call to `document.fonts.load()` be a solution for this scenario, and if so would you be open to that? Any other suggestions (run a build with native support disabled)? Thanks!

**Comment by bcamper** [comment]
@bramstein I tried a build that calls `document.fonts.check()` first, and if that returns false, continues on the original `document.fonts.load()` path: https://github.com/tangrams/fontfaceobserver/commit/5c260094d198b8128c9ff52de0d39bebd0d6d6ac. This works for me to detect system fonts alongside web fonts with native `FontFaceSet` in Chrome and FF.

I'd appreciate any feedback you have on this, does it make sense to you? (This issue seemed like the relevant place to put it, but apologies if not!)

**Comment by rhawbert** [comment]
Looks like `Promise.all()` fails on Google Chrome 49 (Safari 9.1 is ok thou). 
Probably it is using the polyfill instead of native promises. 

When loading a local (custom) font using `font.load()` it works accordingly on both browsers.

The error message: 
`Uncaught (in promise) TypeError: Cannot read property 'classList' of null(…)`

**Comment by vijayaraghavanramanan** [comment]
@rhawbert 

Are you changing body class instead of html class? I remember getting such error and then realized that it happened because the body was not ready yet.

**Comment by rhawbert** [comment]
@vijayaraghavanramanan I've tried both ways, the following also don't work: 

`document.documentElement.classList.add('fonts-loaded');`

Not even a console.log because the error occurs before it... in the promise.

**Comment by chrisppp** [comment]
Same problem here as @rhawbert reported. Any ideas on how to solve?

**Comment by bramstein** [comment]
This happens when you have a JavaScript error in your `load().then(function () { ... });`. This is probably unrelated to Font Face Observer. You can debug this by adding a `catch` like so:

```
var font = new FontFaceObserver('My Font');

font.load().then(function () {
   ...
}).catch(function (e) {
  console.error(e);
});
```

**Comment by lemoustachiste** [comment]
Hi, sorry to reopen this thread but I am confused.

I'm trying to set an observer on a likely local font (say for instance Comic Sans MS), but I'm get a Promise rejection. The catch isn't really helpful as it only tells me what my observer object is:

```
something went wrong FontLoader.js?3726*:24 
A {family: "Comic Sans", style: "normal", weight: "normal", stretch: "normal"}
```

Forking the example of @jaicab, I managed to do what I wanted: https://jsbin.com/qumosinale/1/edit?html,css,js,console,output

So I guess my question is, as I couldn't find anything clear about it, is the loading of local fonts supported? And if yes, what should my set up look like?

Right now this is what I am doing:
```javascript
constructor (props) {
    super()
    this.observer = props.fonts.map((font) => {
      return new FontFaceObserver(font)
    })
  }

  componentDidMount () {
    this.observer.forEach((supportedFont) => {
      supportedFont.load().then((supportedFont) => {
        this.props.onFontLoaded(supportedFont.family)
      })
    })
  }
```

I am creating a tool that allows users to specify the fonts they want, and it can be anything from Google Fonts to Local fonts. So I would very much like to be able to dynamically set my CSS based on the font they are requesting.

**Comment by lemoustachiste** [comment]
Nevermind, nights brings counsel and we are going to try another approach which doesn't involve fontfaceloader in that perspective.

Thanks for the good work!

**Comment by bramstein** [comment]
@lemoustachiste Sorry if this wasn't clear. Loading of local fonts is not supported. It used to be in an older version, but detecting local fonts is incompatible with some of the newer features, so I took it out.
