### ISSUE TITLE
Timeout not working on Chrome and Firefox but working on IE and Safari

### ISSUE THREAD

**Issue by pascalsiegel** [bramstein/fontfaceobserver#56]
Hello,

It seems the timeout is not working on Chrome and Firefox but is working on IE and Safari.
To test I use 6 font and @font-face and different timeout values
Please see below some logs, the NO Font lines is when the timeout is working

Any idea what the issue can be, a bug, a difference in the browser, or just me not understanding the timeout option?
Log for IE or Safari
------------------------
1456633652186 : LOADING FontFaceObserver for font: Dosis400 TimeOut: 4200
1456633652187 : LOADING FontFaceObserver for font: Dosis700 TimeOut: 4800
**1456633652187 : LOADING FontFaceObserver for font: Dosis200 TimeOut: 300
1456633652187 : LOADING FontFaceObserver for font: Dosis500 TimeOut: 500**
1456633652187 : LOADING FontFaceObserver for font: Dosis600 TimeOut: 6600
1456633652187 : LOADING FontFaceObserver for font: Dosis800 TimeOut: 5000
1456633654845 : DOMContentLoaded / font: Dosis400 / (DOMContentLoaded-fontLoading): 2659 / (DomLoadStart-fontLoading): 2543
1456633654845 : DOMContentLoaded / font: Dosis700 / (DOMContentLoaded-fontLoading): 2658 / (DomLoadStart-fontLoading): 2542
1456633654845 : DOMContentLoaded / font: Dosis200 / (DOMContentLoaded-fontLoading): 2658 / (DomLoadStart-fontLoading): 2542
1456633654845 : DOMContentLoaded / font: Dosis500 / (DOMContentLoaded-fontLoading): 2658 / (DomLoadStart-fontLoading): 2542
1456633654845 : DOMContentLoaded / font: Dosis600 / (DOMContentLoaded-fontLoading): 2658 / (DomLoadStart-fontLoading): 2542
1456633654845 : DOMContentLoaded / font: Dosis800 / (DOMContentLoaded-fontLoading): 2658 / (DomLoadStart-fontLoading): 2542
**1456633654867 : NO Font Dosis200 is NOT available, font request FAILED / TimeOut: 300 / failed-loading in: 2680
1456633654867 : NO Font Dosis500 is NOT available, font request FAILED / TimeOut: 500 / failed-loading in: 2680**
1456633654975 : Font Available Dosis400 , class added :wf-Dosis400 ==> font loaded in: 2789
1456633655113 : Font Available Dosis700 , class added :wf-Dosis700 ==> font loaded in: 2926
1456633655116 : Font Available Dosis600 , class added :wf-Dosis600 ==> font loaded in: 2929
1456633655118 : Font Available Dosis800 , class added :wf-Dosis800 ==> font loaded in: 2931
1456633655075 : OnLoadEvent (OnLoadEvent-DomLoadStart(1456633654729): 346

------------------------------------
Log for Chrome or Firefox:
------------------------------------
1456633716799 : LOADING FontFaceObserver for font: Dosis400 TimeOut: 4200
1456633716802 : LOADING FontFaceObserver for font: Dosis700 TimeOut: 4800
1456633716802 : LOADING FontFaceObserver for font: Dosis200 TimeOut: 300
1456633716802 : LOADING FontFaceObserver for font: Dosis500 TimeOut: 500
1456633716802 : LOADING FontFaceObserver for font: Dosis600 TimeOut: 6600
1456633716802 : LOADING FontFaceObserver for font: Dosis800 TimeOut: 5000
1456633718030 : Font Available Dosis400, class added :wf-Dosis400 ==> font loaded in: 1231
1456633718031 : Font Available Dosis700, class added :wf-Dosis700 ==> font loaded in: 1229
**1456633718121 : Font Available Dosis200, class added :wf-Dosis200 ==> font loaded in: 1319
1456633718121 : Font Available Dosis500, class added :wf-Dosis500 ==> font loaded in: 1319**
1456633718178 : DOMContentLoaded / font: Dosis400 / (DOMContentLoaded-fontLoading): 1379 / (DomLoadStart-fontLoading): 1336
1456633718178 : DOMContentLoaded / font: Dosis700 / (DOMContentLoaded-fontLoading): 1376 / (DomLoadStart-fontLoading): 1333
1456633718178 : DOMContentLoaded / font: Dosis200 / (DOMContentLoaded-fontLoading): 1376 / (DomLoadStart-fontLoading): 1333
1456633718178 : DOMContentLoaded / font: Dosis500 / (DOMContentLoaded-fontLoading): 1376 / (DomLoadStart-fontLoading): 1333
1456633718178 : DOMContentLoaded / font: Dosis600 / (DOMContentLoaded-fontLoading): 1376 / (DomLoadStart-fontLoading): 1333
1456633718178 : DOMContentLoaded / font: Dosis800 / (DOMContentLoaded-fontLoading): 1376 / (DomLoadStart-fontLoading): 1333
1456633718182 : Font Available * Dosis600 *, class added :wf-Dosis600 ==> font loaded in: 1380
1456633718190 : Font Available * Dosis800 **, class added :wf-Dosis800 ==> font loaded in: 1388
1456633718295 : OnLoadEvent (OnLoadEvent-DomLoadStart(1456633718135): 160

Best,
Pascal

**Comment by bramstein** [comment]
Thanks for reporting this. It looks like a bug in the new code that uses the native font loading API (on Firefox/Chrome/Opera). I'll try and fix it this week.

**Comment by vijayaraghavanramanan** [comment]
Does this have to do with Unicode Range? Chrome and Firefox have unicode range but not IE and Safari. Dosis seems to be a Google Font which has unicode range in css.

**Comment by pascalsiegel** [comment]
Hello,

Thanks for getting back to me.

I don't think it has to do with the unicode range. I have tryed with @import and @font-face with and without the unicode-range as well as hosting the font localy. the behavior is the same. below are the @font-face:

@font-face {
  font-family: 'Dosis400';
  font-style: normal;
  font-weight: 400;
  src: local('Dosis Regular'), local('Dosis-Regular'), url(https://fonts.gstatic.com/s/dosis/v4/4hYyXH_8WmbBLamf6WjLwg.woff2) format('woff2');
  //unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
@font-face {
   font-family: 'Dosis400';
   font-weight: 400;
   font-style: normal;
   src: url('/sites/all/themes/sk01opw/fonts/dosis/dosis-400-webfont.eot'); // IE9 Compat Modes. But IE9 is OK with Woff  
   src: url('/sites/all/themes/sk01opw/fonts/dosis/dosis-400-webfont.eot?#iefix') format('embedded-opentype'), // IE6-IE8 + IE9 to 10 and edge
       url('/sites/all/themes/sk01opw/fonts/dosis/dosis-400-webfont.woff2') format('woff2'),
       url('/sites/all/themes/sk01opw/fonts/dosis/dosis-400-webfont.woff') format('woff'),
       url('/sites/all/themes/sk01opw/fonts/dosis/dosis-400-webfont.ttf') format('truetype'); // Safari, Android, iOS 
}

**Comment by bramstein** [comment]
It's unrelated to unicode-range. I think I fixed it in v1.6.5, could you give the new version a try?

**Comment by pascalsiegel** [comment]
Just tested, and It is now working on all 4 browser with version 1.6.5. 

Thank you very much, fast and efficient!

**Comment by bramstein** [comment]
Great, thanks a lot for reporting the issue and confirming the fix works!
