### ISSUE TITLE
fontfaceobserver is downloading the font even when not used on the page

### ISSUE THREAD

**Issue by pascalsiegel** [bramstein/fontfaceobserver#57]
@font-face is downloading only the fonts used on the page being displayed but when using fontfaceobserver on a font  it gets downloaded even if not used on the page.

I believe this is the normal behavior and not and bug/issue and mostly would like to confirm.

It is not a major issue but I am thinking of writing some code to take care of this and run fontfaceobserver only for the fonts used on the page. This would be my approach:
1)  Parse the HTML and search for all classes starting with wf- (assuming that the classes used and set are always wf-fontname
2)  Set a cookie listing the fonts for the specific page: fontlist=wf-font1, wf-font2, etc.
3)  Run fontfaceobserver only for the fonts listed in the cookie

This can be done server side with some PHP (I use Drupal), or in Javascript client side. I think server side is better/ more efficient but there will be some issues with caching with things like varnish (they can be solved but it introduces complexity).

Has anyone had some experience with this or are there other options/ solutions?

Best,
Pascal

**Comment by bramstein** [comment]
This is by design. It's mostly to stay compatible with the behaviour on older browsers, where the font load detection implementation triggers font loading.

I don't know your specific use-case, but if you only have a couple of fonts, and you're asynchronously loading them, it doesn't hurt that much to load all of them (of course, this can get out of hand if you're loading a lot).

**Comment by pascalsiegel** [comment]
OK, so it is by design. 
Just to explain a bit what I am doing or trying to do:
I don't have a specific use case, I have been working on clearly understanding how browsers behave, when they do the rendering/painting, when and how they downloads an execute JavaScript, CSS, when the events are trigger, etc. All a long I have been looking at performance and discovering challenges, web-fonts is a good one. They main challenge I believe is that it really depends on the browser! 

I trying to find (and implement) the optimal way to use web-fonts, without compromising on the user experience. I don't plan to have more than 3 or 4 font files, so you are correct, not really an issue in most cases. But ...

The issue I can see with downloading more fonts than needed for a page is on slow networks: 2G for example, or wifi in your preferred coffee shop or airport. 
It looks like the browsers download first CSS and then JS (except Firefox that does JS first, then CSS), then they download all fonts and some pictures in the mix. 
Downloading about 100KB of fonts not used on the page will slow the picture download. Based on the google development tool, a good 2G connection is:  450 Kb/s (56KB/s) and 150 RTT, so it will take about/ at least 2 seconds to download the unused fonts. Since the pictures and fonts get downloaded in parallel, it will add some time to the picture download time and they will display about 3 to 5 seconds after the first time the page has been displayed/ or progressivly, but the final end where everything is displayed is going to take at least 3 seconds longer for unused fonts.

On a regular 2G connection ( 250 Kb/s (31KB/s) and 300 RTT) the 100 KB would cost about 4 seconds, and most likely more due to retry. 

Not downloading the unused fonts would allow to win this 2 to 4 seconds (at least). It will also remove the re-render and re-paints when the fonts are ready and the class is added to the HTML tag.
 

So, overall, if it is not adding to much complexity I think  it is worse doing.
But I am wondering what the best (or a good) solution would be?
