### ISSUE TITLE
FOUT on slow devices even when fonts have been downloaded

### ISSUE THREAD

**Issue by pascalsiegel** [bramstein/fontfaceobserver#58]
I noticed that there can be an FOUT on slow devices. For example an old smartphone or tablet or when a use Virtualbox with Mac OS X and Safari. The FOUT is happening even when the font has been already downloaded, it is very short but still, it is.

From what I could observe it seems to come from the time it takes fontfaceobserver to apply the class when it detected the font is available, and then for the devices to do the re-render and re-paint. So the solution is to set the class base on a cookie that is when the font has been download (font-x-available=1 cookie). So far so good, this is working.

But there is an issue when a user is refreshing/ reloading the page (F5 or click on the refresh), the cookie saying the font is available is still there, the class gets added but the font needs to be downloaded. The issue is not the FOUT but the fact that the font/text doesn’t have the same width and there is a major re-layout or re-flow happening.

My solution so far is to detect the reload/refresh by looking at HTTP_CACHE_CONTROL on the server side (I could not find how to do this on the client side):
1)  when it is a reload set a “reload=1” cookie (server side).
2)  On the client side, if the cookie reload=1 is set: do not add the font classes that would be added based on the font-x-available cookie, and delete the cookie. This makes the page load as it would be the first ever time following the usual process.

Network speed has no influence on the FOUT on slow devices, the FOUT is happening anyway, but slow network makes the re-paint/ re-flow just worse.

I am aware this is somewhat overdoing it! I was wondering if other people have seen this FOUT + re-paint on slow devices. And if there is another way to take care of the slow device + reload issue.

Best,
Pascal

**Comment by vijayaraghavanramanan** [comment]
Don't know much about your point on reload but yes cookie (or something equivalent like local storage or session storage) required for second load as argued here: 

https://www.filamentgroup.com/lab/font-events.html

What I observe is sometimes cookies are also slow (probably asynchronous) and I get a FOUT. So one trick is to have .fonts-loaded as an html class and remove it if no cookie. That way a page can paint with an html class .fonts-loaded before cookie is checked and there's no FOUT.

**Comment by vijayaraghavanramanan** [comment]
For refreshes, since there will be very less number of users doing it, you can simply block css render for second load for all visits. For most users it won't matter as the fonts are from cache.

**Comment by pascalsiegel** [comment]
Thanks, I read all the filamentgroup posts and a number of others. The idea is to set a cookie once the font has been available (on the first download). The problem with the cookie is that if there is a refresh or the user clear the cache, the cookie is still set and the classes get added to the HTML tag before the fonts are ready (fontfaceobserver is the firs javascript to run). 
Im not sure I fully understand your process, but it seems adding the class .fonts-loaded by default and removing it based on a cookie is going to generate problems when there is a refresh or cache clear, the cookie will still exist and fonts won't get downloaded. Correct?

**Comment by bramstein** [comment]
There is also some weird bug in Safari, where it briefly renders a page without fonts before applying cached fonts. There is some more information in this thread: https://github.com/bramstein/fontfaceobserver/issues/35

As for setting a cookie; have a look at using `sessionStorage` instead. It is much more lightweight and doesn't suffer from some of the drawbacks of cookies. For example, what would happen if your cookie is still set, but the browser has deleted the font from its cache? Having FOUT once per browsing session isn't that bad (or you could implement FOIT for the first load and use the `sessionStorage` trick for subsequent views if you really don't want FOUT).

**Comment by pascalsiegel** [comment]
I had a look at session and local storage, I understood that they are not available in Private Mode browsing, kind of an issue! Correct?

I had read thread #35, I haven't observers that kind of behaviors and I am not sure it applies.
I think there are multiple issues overlapping, one of them being the speed of the computer at the specific time of adding the class to the html tag and triggering the re-render and re-paint. 

What I have observered (nothing scientific here) is that the fonts get downloaded from the server or from the cache last (after JS, CSS and even some images. The end of the font donwload is very close in time to DomContentstart and End, plus a little delay for fontfaceobserver to notice the end of the download and return the info.

Adding the cookie trick after the first download somewhat solve this but since foncefaceobserver is running after the cookies are set, it will add the class again. Sometimes early enough, sometime not.

I think the trick that did it for me is in the .check function to set the font class if it has not already been set (based on the cookie),  but set the class in .check only if it is a refresh/reload. 

This allows to not trigger a new or one more paint. I think the .check is triggered very closely in time to the first paint and will trigger another paint or -repaint. Not a problem on a fast device, but it becomes visible on a slow device.

Does this make any sense?













.

**Comment by vijayaraghavanramanan** [comment]
> I had a look at session and local storage, I understood that they are not available in Private Mode browsing, kind of an issue! Correct?

I just tested. Session Storage works in private mode in Chrome. 

About fontfaceobserver adding classes, you can design your code for fontfaceobserver to run only in the first run in one session. 

Such as 

`if(sessioStorage.getItem("enhanced"){
   
}

else {
  //fontfaceobserver codes here
 sessionStorage.setItem("enhanced", "true");
}
`

**Comment by joacim-boive** [comment]
@vijayaraghavanramanan 
That won't work, at least not, in Safari for Mac and iOS in Private Mode.

**Comment by vijayaraghavanramanan** [comment]
@joacim-boive 

Correct. 

I just checked the "Known Issues" tab here 

http://caniuse.com/#feat=namevalue-storage

and it say what you say. Android browser also does that. 

So you have to do a feature detection and use the code in the first part of the if statement in the below code: 

```
function storageAvailable(type) {
	try {
		var storage = window[type],
			x = '__storage_test__';
		storage.setItem(x, x);
		storage.removeItem(x);
		return true;
	}
	catch(e) {
		return false;
	}
}

if (storageAvailable('localStorage')) {
	// Yippee! We can use localStorage awesomeness
}
else {
	// Too bad, no localStorage for us
}
```

Code from here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
