### ISSUE TITLE
BESbswy shows up in Google Web Light

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [bramstein/fontfaceobserver#59]
@bramstein 

The string BESbswy shows up in Google Web Light. Demo [here](http://googleweblight.com/?lite_url=http://www.concertedaction.com/2016/03/13/the-paradox-of-protectionism/) at the bottom of the page: 

It's obviously a Google Web Light bug, but I don't know to whom to report so maybe you can report it to them or I can. Or you may want to change your code if you think it'll take time for them to correct it.

**Comment by bramstein** [comment]
@vijayaraghavanramanan I'm not sure what Google Web Light is, but any modern browser should no longer display that string. Maybe they're running an old copy of the Web Font Loader? Either way, there isn't much I can do (I don't work at Google).
