### ISSUE TITLE
Page not loading at the top

### ISSUE THREAD

**Issue by conormcafee** [bramstein/fontfaceobserver#60]
Hi Bram, 

I think I may have came across an issue with FFO on iOS (both Safari & Chrome).

When I start navigating through a website which uses FFO it starts to act funny, in that the website starts loading the pages one-third (roughly) down, rather than the top of the page.  This results in the user having to scroll to the top.  Just wondering if this is something that you have came across before?

It could well be that I am doing something wrong - but I have implanted FFO into 3 sites now and they are all doing the same.  When I remove the FFO script normality resumes.

Examples repo - https://github.com/conormcafee/fearon-bros/blob/gh-pages/build/js/fontFaceObserver.js
Example Site - http://www.fearonbros.co.uk

**Comment by bramstein** [comment]
I haven't seen this behaviour before, and I'm not sure what could be causing this. I tried to reproduce it but couldn't. Is there any particular version of Safari on iOS that displays this behaviour?

**Comment by bramstein** [comment]
Closing this issue since there has been no response since April. Feel free to re-open it if you're still having this issue.

**Comment by gregorybellencontre** [comment]
Hello

I'm facing the same issue. I automatically skip my header bar (with a jquery scrolltop).
It works well, but when the page is completely loaded, FFO scrolls back to the top.

I don't understand why ...
