### ISSUE TITLE
Safari issues with icon fonts

### ISSUE THREAD

**Issue by djmtype** [bramstein/fontfaceobserver#63]
Chrome and Firefox have no problems with icon fonts, but Safari will fail and prevent any fonts called with Font Face Observer from loading. 

I am using [weathericons](https://erikflowers.github.io/weather-icons/) which match up with Yahoo weather codes, so it's kinda essential to use a font rather than svg images. 

```
(function( w ){
	// if the class is already set, we're good.
	if( w.document.documentElement.className.indexOf( "fonts-loaded" ) > -1 ){
		return;
	}
	var fontA = new w.FontFaceObserver( "Open Sans", {
		weight: 400
	});
	var fontB = new w.FontFaceObserver( "Open Sans", {
		weight: 600
	});
	var fontC = new w.FontFaceObserver( "Open Sans", {
		weight: 400,
		style: "italic"
	});
		var fontD = new w.FontFaceObserver( "Open Sans", {
		weight: 600,
		style: "italic"
	});
	var fontE = new w.FontFaceObserver( "weathericons" );
	w.Promise
		.all([fontA.check(), fontB.check(), fontC.check(), fontD.check(), fontE.check()])
		.then(function(){
			w.document.documentElement.className += " fonts-loaded";
			console.log('fonts loaded');
		});
}( this ));
```

**Comment by bramstein** [comment]
You may want to pass a custom test string for the weathericons font. It probably doesn't contain the default character set that Font Face Observer tests for. You can read more about this in the README (https://github.com/bramstein/fontfaceobserver/blob/master/README.md). Let me know if you have any questions.
