### ISSUE TITLE
Firefox 24 & lower support

### ISSUE THREAD

**Issue by mjc666** [bramstein/fontfaceobserver#66]
Is Firefox 24 & lower supported?  I can't get the FontFaceObserver to resolve with these browsers.  Latest FontFaceObserver (v1.7.1) used with your polyfill.

See Demo - works in all browsers but FF 24 & lower:
https://jsfiddle.net/ego84zav/7/

I used browerstack to test with older version of firefox.

Matt

**Comment by bramstein** [comment]
It should be. I'll have a look at this, thanks for reporting.

**Comment by vijayaraghavanramanan** [comment]
I think older versions of Firefox evaluate `!!window.FontFace` to `true` even though they don't have that feature. So it's a false positive.

**Comment by bramstein** [comment]
Thanks, that's interesting. I'll look into it.

**Comment by bramstein** [comment]
This should be fixed in v2.0.2. Thanks for the research @vijayaraghavanramanan.
