### ISSUE TITLE
Promise not resolving with font web service

### ISSUE THREAD

**Issue by qasimalyas** [bramstein/fontfaceobserver#68]
Hi,

This is more of a question than an issue. 

I have an example where I'm using a google webfonts as the font service. I'm using the example from the fontfaceobserver.com and my promise seems to be rejecting. 

If i try the same example with a local fonts (same one) and change my references in CSS, the promise resolves and I get a console logged.

Am i doing something wrong when it comes to remote font services or is this not supported hence the promise rejecting?

I've uploaded my example to github https://github.com/qasimalyas/fontsobserver 

Many thanks

**Comment by bramstein** [comment]
Both approaches should work. Is it possible you have the font installed locally as well? Google Fonts uses locally installed fonts when they are available and this throws off the web font load detection.

**Comment by qasimalyas** [comment]
No I don't have the font installed locally at all. I did link to my example which is reproducing the issue when running it locally https://github.com/qasimalyas/fontsobserver

Any help would be appreciated.

**Comment by qasimalyas** [comment]
Update: I switched to using typekit as a font service and that works fine. Promise is resolved. Something not right with google fonts.

[master branch](https://github.com/qasimalyas/fontsobserver/tree/master) == google fonts
[typekit branch](https://github.com/qasimalyas/fontsobserver/tree/typekit) == typekit

**Comment by aried3r** [comment]
I'm not sure if this is related, since 2.x was only released after this issue was created, but I have a similar problem.

I'm using poltergeist/PhantomJS with Capybara in my Rails request specs and it used to work fine with v1.7.x of fontfaceobserver, but updating to 2.x throws the following errors:

```
ReferenceError: Can't find variable: Promise
ReferenceError: Can't find variable: Promise
ReferenceError: Can't find variable: componentHandler
ReferenceError: Can't find variable: componentHandler
```

I couldn't find the code between 1.7.5 and 2.0.1 that introduced this behavior.

**Comment by aried3r** [comment]
I don't know what changed, if these are indeed the only changes, then there's nothing I can make out that would cause this.

https://github.com/bramstein/fontfaceobserver/compare/v1.7.1...v1.7.2

**Comment by tragiclifestories** [comment]
@aried3r and anyone else looking at similar problems - this might be an issue with phantom. Explicitly assigning bluebird or similar to `window.Promise` in a test helper file could fix it (did for me).

**Comment by aried3r** [comment]
@tragiclifestories that's great to hear! Would you mind sharing the code you used to fix this issue?
