### ISSUE TITLE
Fallback when javascript is disabled

### ISSUE THREAD

**Issue by felixsanz** [bramstein/fontfaceobserver#69]
In your article you said:

> This will load each web font in­de­pen­dently, which is use­ful when the fonts are un­re­lated and sup­posed to ren­der pro­gres­sively (i.e. as soon as they load). Un­like the na­tive font load­ing API you don’t pass font URLs to Font Face Ob­server. **It will use the @font-face rules al­ready avail­able in your CSS to load fonts. This al­lows you to load your web fonts man­u­ally us­ing JavaScript, with a grace­ful degra­da­tion to ba­sic CSS.**

What graceful degradation? Even if you add the `<link>` tags inside `<noscript>` or just have the `@font-face` declarations in your CSS it won't work. Because no javascript means no `fonts-loaded` class in `<html>`, so the custom fonts will never display.

What i'm missing?

**Comment by localnerve** [comment]
Just a thought: Can you code (in your html) a "no-js" class (that also matches) that you remove before your fontfaceobserver code runs? Would that work?

**Comment by felixsanz** [comment]
Yea, maybe i could add `no-js { font-family: }` or something like that :+1:
