### ISSUE TITLE
Improve compression rate

### ISSUE THREAD

**Issue by albertogasparin** [bramstein/fontfaceobserver#7]
Do you have any plan to improve the compression rate of this fantastic lib?
For instance, by passing `window` and `document` vars to the wrapper function they can get minified. Or by using some vars to "cache" some repeated strings or the `this` keyword, so the compressor can better minify them.

**Comment by albertogasparin** [comment]
After further inspection, I think the issue is caused by the compressor itself.
Your source code is (in some situations) more compact than the compressed output. :disappointed: 
By replacing some bits of the compressed output with your original source code, Uglify managed to get ~10% reduction (more than 500 chars). Just to let you know...

**Comment by bramstein** [comment]
Hmm, that's a good question :smile: 

I don't like optimisations that make the source code hard to maintain or unreadable, but anything else is fair game. You also have to keep in mind that I expect most people to serve their JavaScript gzipped, so repetitive things like `this`, `function` are maybe not worth optimising.

With that said, I'd like to see what Uglify does to make to code that much smaller.

**Comment by bramstein** [comment]
I've tried various changes, but the resulting decrease in GZIP'd size is negligible. I think I'll keep the code as it is for now. Feel free to re-open with concrete ideas for improving the minification/compression rate.
