### ISSUE TITLE
Changelog for v2

### ISSUE THREAD

**Issue by joaocunha** [bramstein/fontfaceobserver#72]
I had issues trying to figure out what were the breaking changes for v2.

A `CHANGELOG.md` + release notes would certainly do no harm.

Great job with the lib nevertheless.

**Comment by 0x80** [comment]
+1 The breaking change removal of .check() was not clear. In the commit it says it was deprecated but I have never seen a warning before

Also I was wondering why you use the array syntax in various places in the code?

```javascript
 window['FontFaceObserver'] = fontface.Observer;
 window['FontFaceObserver']['prototype']['load'] = fontface.Observer.prototype.load;
```

**Comment by bramstein** [comment]
There were two breaking changes:

* `check` has been renamed to `load`. This check method has been aliased to `load` for many 1.x versions and in the documentation, but in 2.x the `check` method has been removed.
* CommonJS modules are now default. Previously there were supported but the module also exposed `FontFaceObserver` on the global window object. This is no longer the case when you include Font Face Observer as a module (including the JS file still works as expected).

I'll include a CHANGELOG from now on, thanks for the suggestion.

**Comment by bramstein** [comment]
@0x80 The array syntax is for Closure Compiler's advanced optimization mode. When the code is compiled the array notation is removed. The deprecation warning should have been shown when compiling the code. I opted not to show it while running the code.

**Comment by ahstro** [comment]
Still not seeing a `CHANGELOG.md` anywhere, nor any info in the "Releases"-tab. Might I suggest checking out [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) for both the *why* and the *how*? 🙂

**Comment by testacode** [comment]
This would be awesome man. It's like having an utility but no explanation manual.
