### ISSUE TITLE
Use passive scroll event listeners

### ISSUE THREAD

**Issue by jbmoelker** [bramstein/fontfaceobserver#75]
Currently the [scroll event listeners](https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js#L126) are active listeners. These [affect the scrolling performance](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#the-problem) of the webpage using the FontFaceObserver. As [`onScroll`](https://github.com/bramstein/fontfaceobserver/blob/master/src/ruler.js#L110) is not cancelling the event, my suggestion would be to *use passive event listeners*.
 
Since this module uses [`closure-dom`](https://github.com/bramstein/closure-dom) (also by @bramstein) to bind to the scroll events, I'm not sure how best to change this behaviour. I could add a `dom.supportsPassiveEventListener` based on this [feature detection script](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection). But I'm not sure if [`dom.addListener`](https://github.com/bramstein/closure-dom/blob/master/src/dom.js#L108) should always be `element.addEventListener(event, callback, dom.supportsPassiveEventListener ? {passive:true}, false)` as the `dom-closure` API is not documented anywhere and I also don't know what other modules may be using it.

@bramstein do you agree this is an issue? And do you know how / where we can best solve it? I'd be happy to help.

Another note: am I missing something or should the event listener still be removed at some point?

**Comment by bramstein** [comment]
I'm not sure this is worth doing. The browsers that support passive scroll events also support the native CSS font loading API. Font Face Observer will use the native font loading API when it is available, so this optimisation won't have any effect on those browsers. We can reconsider this when some browser implements passive scroll events and not the font loading API.

The event listeners should be removed automatically when the element is removed (and is garbage collected).

**Comment by jbmoelker** [comment]
@bramstein I agree. Was still using v1.6.5. But I see [`.supportsNativeFontLoading()`](https://github.com/bramstein/fontfaceobserver/commit/f80831fbab3c18f464f873f029ebeb1304301a73#diff-08f3e9ab539253c87ea111cc61c69e29R92) was added in v2.x. 

Thanks for the quick response. I'll close the issue.
