### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by djmtype** [bramstein/fontfaceobserver#77]
After updating this script, I'm getting this error: 

`fonts.js:28 Uncaught TypeError: fontA.check is not a function`

Using this method that worked previously: 

```
(function( w ){
  if( w.document.documentElement.className.indexOf( "fonts-loaded" ) > -1 ){
    return;
  }
  var fontA = new w.FontFaceObserver( "Lato", {
    weight: 400
  });
  var fontB = new w.FontFaceObserver( "Lato", {
    weight: 600
  });

  w.Promise
    .all([fontA.check(null, 5000), fontB.check(null, 5000)])
    .then(function(){
      w.document.documentElement.className += " fonts-loaded";
      console.log('Font is available');
      }, function () {
        console.log('Font is not available');
    });
}( this ));
```

**Comment by XhmikosR** [comment]
This is normal since v2.x removed `check()`. Use `load()` instead.

https://github.com/bramstein/fontfaceobserver/commit/5e2fa3372ace46001eb19ff11994be6699c6bfde

**Comment by bramstein** [comment]
Yes, sorry about that. The `check` method has been deprecated for a year and the 2.x release finally removed it. The semantics are exactly the same, so you can just replace `check` with `load`.
