### ISSUE TITLE
Not working on iOS 10 

### ISSUE THREAD

**Issue by zenderol** [bramstein/fontfaceobserver#79]
On iOS 10, iPhone (Golden Master) in Safari the fonts are not registered by the fontfaceobserver. Even though the fonts are loaded (as seen in the network tab in safari's dev-tools), the fonts are not registered by the observer. This issue occurs only when returning from inactivity mode. For example: Closing the browser and starting it again and the same page is loaded. The issue can be reproduced on this page:

https://www.zachleat.com/web-fonts/demos/critical-foft-data-uri.html

As iOS10 is coming out next week, it would be really great if we could find a quick fix.

**Comment by bramstein** [comment]
I can't reproduce this (on either iOS or OS X). Zach's page also appears to load correctly for me. Do you have any details, or a stack trace so I can look into it? Thanks!

**Comment by zenderol** [comment]
Here are the exact steps to reproduce the issue on iOS 10 (with Zach's page):
 1. Open Safari/Chrome und navigate to the page
 2. Close Safari using the iOS's default App Switcher (double tap on the Home button, and close Safari/Chrome)
 3. Reopen Safari/Chrome and see how to Zach's page is loaded without webfonts

The error what I get is that the timeout of observer.load expries and the correct font style classes are not added to the <html> tag, eventhough the fonts can be seen in the network tab of the dev-tools.

**Comment by mbeswetherick** [comment]
Hey, Bram!

I spoke with "Enatario" and she fixed her problem by updating node. I however am using your polyfill that includes the promise. Did you happen to see if that was working or were you just looking at it in a node context?

**Comment by diniscorreia** [comment]
Hi @bramstein 

I'm having the same problem - I can see the fonts in the network tab but the code in `.then()` doesn't run.

**Comment by diniscorreia** [comment]
Really seems like an iOS issue - both Chrome and Safari are affected, but doesn'y happen on desktop Chrome (even with throttling - I though it could just be the timeout) or Chrome on Android.

**Comment by bramstein** [comment]
Hey, I think this is actually caused by a bug in Safari 10. I've opened up a pull request for a possible workaround, see #86.

**Comment by zenderol** [comment]
@bramstein great, thank you!

**Comment by bramstein** [comment]
Could you try v2.0.6? I think it works around the issue by disabling use of the native font loading API on Safari 10.
