### ISSUE TITLE
Timeout wisdom

### ISSUE THREAD

**Issue by rarkins** [bramstein/fontfaceobserver#80]
Has anyone done any study or reasoning into timeout values for this library and what to use? I see quite a lot of timeouts in production and here is the split:

![image](https://cloud.githubusercontent.com/assets/6311784/18437244/409bb584-78fc-11e6-8a49-2882398785e9.png)

I'm torn between raising the default value versus avoiding a "jarring" switch for users if font changes really late.

**Comment by bramstein** [comment]
No, I haven't done much research into this. FFO is using the same timeout that browsers have adopted for loading fonts. I'm very interested to hear if you have more data (you can pass a custom timeout as the second parameter to `load` if you want to experiment).

My personal preference would be to not show web fonts if they take more than 3 seconds to load.

**Comment by SampsonCrowley** [comment]
@bramstein I completely agree with you for readable fonts.

My only use case where I think there should be an option to disable the timeout completely would be icon fonts. Icon fonts are probably poor UI at their root, but when they _are_ used, it would be nice to have an option to set it so they would load no matter how long it takes

**Comment by DanielPower** [comment]
@SampsonCrowley if you don't want a timeout value, you can set the timeout to an arbitrarily large number or `Infinity`.

**Comment by SampsonCrowley** [comment]
@DanielPower yeah, I wish it was that simple. Already tried infinity

**Comment by DanielPower** [comment]
It looks like 2147483647 is the largest value you can pass in, because under the hood it uses a `setTimeout`, which stores its time as a 32bit integer. That's a little over 24 days.

Source: https://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values

It's not elegant, but it should be longer than the network request timeout for loading the font.
