### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by JimmyRittenborg** [bramstein/fontfaceobserver#82]
Your docs says that fonts for the @font-face could be provided by Google Fonts. But it seems that Google haven't made loading their font this way anything near easy at all?

**Comment by bramstein** [comment]
@JimmyRittenborg You can include the `<link rel="stylesheet" href="...">` from Google Fonts and then use one of the [font loading patterns](https://www.bramstein.com/writing/web-font-loading-patterns.html).

For example here's to avoid the flash of invisible text:

```html
<head>
  <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
  <script>
    var script = document.createElement('script');
    script.onload = function () {
      var bree = new FontFaceObserver('Bree');

      bree.load(function () {
        document.documentElement.classList.add('fonts-loaded');
      });
    };
    script.src = "/path/to/fontfaceobserver.js";
    document.head.appendChild(script);
  </script>
  <style>
    html {
      font-family: Georgia, serif;
    }

    html.fonts-loaded {
      font-family: Bree Serif, Georgia, serif;
    }
  </style>
</head>
```

**Comment by jwbats** [comment]
@bramstein I want to use FontFaceObserver to load fonts of which the @font-face declaration has just been loaded by dynamically adding a link element in the head. I don't want to have to reload the FontFaceObserver script every time I select a google font from a select box.

So far, this script works well:

```
		$(function(){
			var link = '<link href="https://fonts.googleapis.com/css?family=Erica+One" rel="stylesheet">';
			$('head').append(link);
		
			var font = new FontFaceObserver('Erica One', {
			  weight: 400
			});

			font.load().then(function () {
			  console.log('success');
			}, function () {
			  console.log('fail');
			});
		});
```

But, using this code, can I be sure that the @font-face declarations have been loaded before FontFaceObserver starts downloading the actual font binaries, across all browsers?

GoogleFontLoader is randomly crapping out on various fonts and I am in need of a dynamic font loading solution that will work realiably, every single time. At this point, I'm not so worried about FOUTs anymore, although ideally I'd avoid those too. Any suggestions welcome.
