### ISSUE TITLE
Bug when using loadCSS?

### ISSUE THREAD

**Issue by diniscorreia** [bramstein/fontfaceobserver#84]
I previously left a comment on #79 because I was having issues on iOS - turns out I (sort of) pinned down the cause and it seems to be related to [loadCSS](https://github.com/filamentgroup/loadCSS)

Whenever I use it to load my non-critical CSS, I have intermittent issues on iOS with the promise not resolving (the fonts do load and show up on the network tab). I have my font-face declarations inlined on my critical CSS, so the file I'm loading with loadCSS doesn't have any declarations.

It almost seems like a race condition, because sometimes works, sometimes doesn't. But it only happens on iOS.

I also [opened an issue on loadCSS repository](https://github.com/filamentgroup/loadCSS/issues/192) and have set up a [(terrible, css-ridden) test case](http://diniscorreia.com/debug/fontface.html).

Any ideas? I really have no idea what might be causing it. If I don't run loadCSS everything works.

**Comment by bramstein** [comment]
Interesting. Thanks for the test case. I'll see if I can reproduce it and figure out what is happening.

**Comment by diniscorreia** [comment]
@bramstein not sure if it helps, but I also tried using Web Font Loader and the same thing happened.

**Comment by diniscorreia** [comment]
@bramstein chiming in with probably-not-that-helpful inputs :) Could this be a bug in iOS's Font Load API? It seems to work if I edit the script code that tries loading the fonts with the Promise and API.

**Comment by scottjehl** [comment]
is this specific to a particular version of iOS? thx!

**Comment by diniscorreia** [comment]
@scottjehl I can only reproduce it on iOS 10 (happens both on Safari and Chrome).

Like I said, only happens sometimes - if I open the test case and keep refreshing the page, sometimes the fonts will load, sometime won't.

Also, I'm declaring @font-face on the inlined CSS, the file I'm loading with loadCSS has no font-face declarations.

**Comment by scottjehl** [comment]
ok. thanks. and I suppose your use of those custom fonts is qualified to some class selector that you add via observer?

**Comment by diniscorreia** [comment]
@scottjehl correct - some of those are inlined on the critical css, others on the deferred css file.

**Comment by scottjehl** [comment]
Okay thanks. Sounds standard.

**Comment by diniscorreia** [comment]
@scottjehl and @bramstein, managed to add some breakpoints - when the Promise fails, the link for css file still has the "only x" media. When it does resolve, the link already has a media="all" 😕

**Comment by scottjehl** [comment]
Hmm. I'm having trouble reproducing this in iOS10 on two sites that use both loadCSS and ffobserver in this same way.

Can you check if the following sites give you font trouble?

https://www.filamentgroup.com/
http://www.vineyardvines.com/womens-clothing/

Maybe theres an implementation difference to consider. Or a ffobserver version diff?

**Comment by diniscorreia** [comment]
@scottjehl So, just tried the exact same loadCSS (plus the other scripts in the same script tag) and ffobserver on vineyardvines.com - I just changed the link the CSS file and the two fonts being loaded and it still fails sometime. [Test case](sftp://ftp.diniscorreia.com//home/dinisperu/diniscorreia.com/debug/s2008.html).

The only other difference is that I'm calling ffobserver right after the css in the head, as opposed to the bottom of the page in your example.

**Comment by scottjehl** [comment]
okay thanks, that’s something I guess. 
We always inline FFobserver at the bottom to save room in the head for critical assets. Does your case become consistent if ffobserver is at the end?

**Comment by diniscorreia** [comment]
[Updated test case](http://diniscorreia.com/debug/s2008.html) - added a bunch of dummy content, moved ffobserver to the bottom and now it actually seems to fail more often. 

Could this be a FontLoading API bug? If I edit out the native API bit from ffobserver it works every time.

**Comment by zenderol** [comment]
I can also confirm this issue. It happens only when using the included polyfil of loadCSS (cssrelpreload.js)

**Comment by diniscorreia** [comment]
@zenderol I've tried calling the function directly and the same thing happens.

**Comment by liltinkerer** [comment]
Do you host your own fonts? I can't replicate it using Google fonts.

@zenderol @diniscorreia

**Comment by liltinkerer** [comment]
Could [this](https://github.com/bramstein/fontfaceobserver/issues/85) issue be related to the problem?

**Comment by diniscorreia** [comment]
@liltinkerer I do host the fonts - but the fonts are declared on the critical (inlined) css.

And it's actually the opposite of that issue - the promise does not resolve, *but* the font is still loaded (I can see it in the network tab). Also, it only happens on iOS, can't reproduce the issue on desktop Safari.

**Comment by diniscorreia** [comment]
So, terrible workaround but I'm basically adding an extra check to `if(Observer.supportsNativeFontLoading())` to exclude iOS devices (based on user agent) until this is fixed. Like I said, seems to be related to the implementation of the native font loading API.

**Comment by bramstein** [comment]
I think it is related to this bug: https://bugs.webkit.org/show_bug.cgi?id=164902

I'm working on a fix.

**Comment by diniscorreia** [comment]
@bramstein Yep. I said I couldn't reproduce on desktop Safari but I'd only teste on Safari 9. Safari 10 - which does support the API - seems to have the same problem (added *another* hacky browser check to my code in the meantime).

**Comment by bramstein** [comment]
The fix I was working on doesn't work either due to a related bug: https://bugs.webkit.org/show_bug.cgi?id=165037

I think the best way forward is to disable native font loading on Safari 10 (for now).

**Comment by bramstein** [comment]
Opened a pull request for the proposed change in #86.

**Comment by bramstein** [comment]
Could you try v2.0.6? I think it successfully works around issue.

**Comment by liltinkerer** [comment]
@diniscorreia Does v2.0.6 fix the issue? I'm having problems replicating the same bug with the older version also, so I can't really tell any difference.
