### ISSUE TITLE
CDN recommended settings?

### ISSUE THREAD

**Issue by yumyo** [bramstein/fontfaceobserver#87]
Hi,

loading my font files via KeyCDN triggers random Uncaught (in promise) errors, sometimes for one font, sometimes for another, at times it just works as expected.

Serving the fonts from within my own domain present no issues. Any hint?

**Comment by bramstein** [comment]
It only rejects the promise when the fonts fail to load. You can try increasing the timeout to see if that makes the problem go away. If it does, you'll need to look into why the CDN isn't performing as expected.
