### ISSUE TITLE
Example throws error

### ISSUE THREAD

**Issue by eenagy** [bramstein/fontfaceobserver#90]
I am trying to setup the basic example as a working solution, but I receive uncaught error in promise and fonts are not loading.

<img width="420" alt="screenshot 2016-12-11 10 37 36" src="https://cloud.githubusercontent.com/assets/4188977/21077919/e7a1198c-bf8d-11e6-9653-dfb62d01e888.png">

Here is the code:

```js
var font = new FontFaceObserver('Roboto', {
  weight: 500
});
 
font.load().then(function () {
  console.log('Font is available');
  document.querySelector(".hello").innerHTML = "Hello World!";
});
```

And here is a jsfiddle demo: https://jsfiddle.net/bdwLy9vk/

Do I miss some setting or this a bug?

**Comment by bramstein** [comment]
I had a look at your demo, and you're not including the CSS @font-face rules for Roboto. In this case Font Face Observer will wait for a bit and then reject the promise. You'll need to include the fonts from somewhere, for example from Google Fonts:

```
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
```

That should make the error go away.
