### ISSUE TITLE
FOIT in Safari

### ISSUE THREAD

**Issue by tigranpetrossian** [bramstein/fontfaceobserver#92]
I'm experiencing FOIT in MacOS Sierra Safari 10.0.1, as if the "fonts-loaded" class is being added too early, resulting in text turning invisible and then sequentially appearing as each font is loaded.

[Video](https://cl.ly/06060F1U0L3L)  
In the video I load the page with clean cache and bandwidth throttled to 3G-ish network. Issue especially affects slower connections which should be the main target for optimization.

[Live example for reproducing](http://perf.tigran.io) (**Need to have Source Sans Pro or Lato locally installed on Mac to reproduce**)

FFO implementation:

    <script>
     var script = document.createElement('script');
     script.onload = function () {
       var lato = new FontFaceObserver('Lato', {
         weight: 400
       });
    
        var latoBold = new FontFaceObserver('Lato', {
          weight: 700
        });
    
        var latoItalic = new FontFaceObserver('Lato', {
          style: 'italic'
        });
    
        var SourceSansPro = new FontFaceObserver('Source Sans Pro');
    
        Promise.all([
          lato.load(null, 3000),
          latoItalic.load(null, 3000),
          latoBold.load(null, 3000),
          SourceSansPro.load(null, 3000)]).then(function () {
          document.documentElement.classList.add('fonts-loaded');
          console.log('loaded!')
        });
      };
      script.src = "/assets/js/vendor/fontfaceobserver.js";
      document.head.appendChild(script);
    </script>

**Update:** Narrowed down to having the font installed locally. In this case, disabling Source Sans Pro in Fontbook was bringing back the normal behavior.

Workaround would be not specifying `local` fonts in `font-face` declaration and renaming the font-family within CSS.

**Comment by zenderol** [comment]
Having the same issue on Safari 10+ but it is not due to locally installed fonts

**Comment by pothi** [comment]
Possibly related to https://github.com/bramstein/fontfaceobserver/issues/38.

**Comment by dmitrizzle** [comment]
Chiming in. Same issue on Safari browsers on iOS and macOS. Chrome works perfectly, as expected, but Safari does not benefit from Font Face Observer. Here's what's happening (on Safari):

1. System fonts appear instantly, everything looks good.
1. FFO requests custom fonts (in my case it's Exo 2 and Lora) and everything goes blank.
1. Custom fonts are loaded, the `.fonts-loaded` class is added to body and we're back in business with nicer typography.

I think the reason is that FFO is being a little over-optimistic in Safari with Promises. Is there a way to convince it to wait until the fonts actually are loaded to add the class? Adding my code below for reference (I'm using [typefaces](https://github.com/KyleAMathews/typefaces) to self-host the fonts):

```javascript
import FontFaceObserver from "fontfaceobserver"
require("typeface-exo-2")
require("typeface-lora")

export const loadFonts = () => {
	const doc = document.documentElement.classList
	if( doc.contains("fonts-loaded") ){ return }
	
	(new FontFaceObserver("Exo 2", {
		weight: 600
	})).load(null, 5000).then(function(){
		doc.add("fonts-loaded-headers")
		
		Promise.all([
			(new FontFaceObserver("Lora", {
				style: "normal",
				weight: 400
			})).load(null, 5000),
			(new FontFaceObserver("Lora", {
				style: "italic",
				weight: 400
			})).load(),
			(new FontFaceObserver("Lora", {
				style: "normal",
				weight: 700
			})).load(),
			(new FontFaceObserver("Lora", {
				style: "italic",
				weight: 700
			})).load(),
		])
		.then(function(){
			doc.add("fonts-loaded")
			//__cookie.set('fontsLoaded', true)
		},
		function(){
			console.log("Lora FAILED")
		})
		
	},
	function(){
		console.log("Exo 2 FAILED")
	})
}
```

And CSS is :
```css
h1 {
    font-family: Arial, sans-serif;
    letter-spacing: 0.005em;
    line-height: 1.15em;
    font-weight: 700;
}
.fonts-loaded h1 {
    font-family: "Exo 2", Arial sans-serif;
    letter-spacing: 0.025em;
    line-height: 1.15em;
    font-weight: 600;
}
```
(^^^ same idea for Lora fonts)
