### ISSUE TITLE
Won't load Fonts with Webpack

### ISSUE THREAD

**Issue by hendrikeng** [bramstein/fontfaceobserver#96]
Hey ,

thanks for your awesome work, i was trying to implement it in a project with
fontfaceobserver and webpack,
it does all work if i implement it using @import url in my app.scss , but as soon as i import the font in my js  it doesn't throwing :

`Uncaught (in promise) A {family: "BentonSans Cond Black", style: "normal", weight: 400, stretch: "normal"}
`
thats the entry.js ...i have no idea why whats causing it to be honest:
```
// Load Benton Sans typeface
import '../fonts/BentonSansCondBlack.css';

// import CSS to bundle it with webpack
import '../scss/app.scss';

const FontFaceObserver = require('fontfaceobserver');

const bentonSans = new FontFaceObserver('BentonSans Cond Black', {
  style: 'normal',
  weight: 400,
});

bentonSans.load().then(() => {
  console.log('Benton Sans has loaded'); // eslint-disable-line
});
```

and thats the css for the font : 

```
@font-face {
  font-family: 'BentonSans Cond Black';
  src: url('BentonSans Cond Black.eot');
	src: url('BentonSans Cond Black.eot?#iefix') format('embedded-opentype'),
		url('BentonSans Cond Black.woff2') format('woff2'),
		url('BentonSans Cond Black.woff') format('woff'),
		url('BentonSans Cond Black.svg#BentonSans Cond Black') format('svg');
    font-weight: 400;
    font-style: normal;
    font-stretch: normal;
    unicode-range: U+0020-02DC;
}
```

**Comment by bramstein** [comment]
I'm just guessing here, but the @font-face rules need to be in the document before the Font Face Observer three second timeout is triggered. If the webpack dev environment takes a bit longer FFO might miss the fonts. If you have a demo page, I could take a closer look.
